# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Tests for the dsql_lint tool in server.py."""

import json
import pytest
from unittest.mock import patch, MagicMock
from awslabs.aurora_dsql_mcp_server.server import dsql_lint


class TestDsqlLint:
    """Tests for the dsql_lint MCP tool."""

    @pytest.mark.asyncio
    async def test_empty_sql_returns_empty_diagnostics(self):
        """Empty SQL input returns empty diagnostics without calling the binary."""
        result = await dsql_lint('', fix=False)
        assert result['diagnostics'] == []
        assert result['fixed_sql'] is None
        assert result['summary'] == {'errors': 0, 'warnings': 0, 'fixed': 0}

    @pytest.mark.asyncio
    async def test_whitespace_only_returns_empty_diagnostics(self):
        """Whitespace-only SQL returns empty diagnostics."""
        result = await dsql_lint('   \n\t  ', fix=False)
        assert result['diagnostics'] == []
        assert result['fixed_sql'] is None

    @pytest.mark.asyncio
    async def test_binary_not_found_raises_exception(self, mocker):
        """Raises exception when dsql-lint binary is not on PATH."""
        mocker.patch('shutil.which', return_value=None)

        with pytest.raises(Exception, match='dsql-lint binary not found'):
            await dsql_lint('CREATE TABLE t (id INT);', fix=False)

    @pytest.mark.asyncio
    async def test_lint_clean_sql(self, mocker):
        """Clean SQL returns empty diagnostics."""
        mock_output = json.dumps({
            'schema_version': 1,
            'files': [{
                'file': '<stdin>',
                'diagnostics': [],
                'error': None,
                'output_file': None,
                'fixed_sql': None,
            }],
            'summary': {'errors': 0, 'warnings': 0, 'fixed': 0},
        })

        mock_run = mocker.patch('subprocess.run')
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout=mock_output,
            stderr='',
        )
        mocker.patch('shutil.which', return_value='/usr/bin/dsql-lint')

        result = await dsql_lint('CREATE TABLE t (id INT PRIMARY KEY);', fix=False)

        assert result['diagnostics'] == []
        assert result['fixed_sql'] is None
        assert result['summary'] == {'errors': 0, 'warnings': 0, 'fixed': 0}

    @pytest.mark.asyncio
    async def test_lint_detects_serial_type(self, mocker):
        """Detects SERIAL type usage."""
        mock_output = json.dumps({
            'schema_version': 1,
            'files': [{
                'file': '<stdin>',
                'diagnostics': [{
                    'rule': 'serial_type',
                    'line': 1,
                    'message': 'Column `id` uses SERIAL, which is not supported in DSQL.',
                    'suggestion': 'Use `BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)` instead.',
                    'fix_result': {
                        'status': 'fixed_with_warning',
                        'detail': 'Replaced SERIAL with BIGINT GENERATED BY DEFAULT AS IDENTITY',
                    },
                    'statement_preview': 'CREATE TABLE t (id SERIAL PRIMARY KEY)',
                }],
                'error': None,
                'output_file': None,
                'fixed_sql': None,
            }],
            'summary': {'errors': 0, 'warnings': 1, 'fixed': 0},
        })

        mock_run = mocker.patch('subprocess.run')
        mock_run.return_value = MagicMock(
            returncode=1,
            stdout=mock_output,
            stderr='',
        )
        mocker.patch('shutil.which', return_value='/usr/bin/dsql-lint')

        result = await dsql_lint('CREATE TABLE t (id SERIAL PRIMARY KEY);', fix=False)

        assert len(result['diagnostics']) == 1
        assert result['diagnostics'][0]['rule'] == 'serial_type'

    @pytest.mark.asyncio
    async def test_fix_mode_returns_fixed_sql(self, mocker):
        """Fix mode returns corrected SQL."""
        fixed_sql = 'CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 ),\n  data TEXT\n);\n'
        mock_output = json.dumps({
            'schema_version': 1,
            'files': [{
                'file': '<stdin>',
                'diagnostics': [{
                    'rule': 'serial_type',
                    'line': 1,
                    'message': 'Column `id` uses SERIAL.',
                    'suggestion': 'Use IDENTITY.',
                    'fix_result': {'status': 'fixed_with_warning', 'detail': 'Replaced SERIAL'},
                    'statement_preview': 'CREATE TABLE t ...',
                }, {
                    'rule': 'json_type',
                    'line': 1,
                    'message': 'Column `data` uses JSON.',
                    'suggestion': 'Use TEXT.',
                    'fix_result': {'status': 'fixed', 'detail': 'Replaced JSON with TEXT'},
                    'statement_preview': 'CREATE TABLE t ...',
                }],
                'error': None,
                'output_file': None,
                'fixed_sql': fixed_sql,
            }],
            'summary': {'errors': 0, 'warnings': 1, 'fixed': 1},
        })

        mock_run = mocker.patch('subprocess.run')
        mock_run.return_value = MagicMock(
            returncode=3,
            stdout=mock_output,
            stderr='',
        )
        mocker.patch('shutil.which', return_value='/usr/bin/dsql-lint')

        result = await dsql_lint('CREATE TABLE t (id SERIAL, data JSON);', fix=True)

        assert result['fixed_sql'] == fixed_sql
        assert len(result['diagnostics']) == 2

    @pytest.mark.asyncio
    async def test_fix_flag_passed_to_command(self, mocker):
        """Verify --fix flag is included in command when fix=True."""
        mock_output = json.dumps({
            'schema_version': 1,
            'files': [{'file': '<stdin>', 'diagnostics': [], 'error': None,
                       'output_file': None, 'fixed_sql': None}],
            'summary': {'errors': 0, 'warnings': 0, 'fixed': 0},
        })

        mock_run = mocker.patch('subprocess.run')
        mock_run.return_value = MagicMock(returncode=0, stdout=mock_output, stderr='')
        mocker.patch('shutil.which', return_value='/usr/bin/dsql-lint')

        await dsql_lint('SELECT 1;', fix=True)

        cmd = mock_run.call_args[0][0]
        assert '--fix' in cmd
        assert '--format' in cmd
        assert 'json' in cmd
        assert '-' in cmd

    @pytest.mark.asyncio
    async def test_no_fix_flag_when_fix_false(self, mocker):
        """Verify --fix flag is NOT included when fix=False."""
        mock_output = json.dumps({
            'schema_version': 1,
            'files': [{'file': '<stdin>', 'diagnostics': [], 'error': None,
                       'output_file': None, 'fixed_sql': None}],
            'summary': {'errors': 0, 'warnings': 0, 'fixed': 0},
        })

        mock_run = mocker.patch('subprocess.run')
        mock_run.return_value = MagicMock(returncode=0, stdout=mock_output, stderr='')
        mocker.patch('shutil.which', return_value='/usr/bin/dsql-lint')

        await dsql_lint('SELECT 1;', fix=False)

        cmd = mock_run.call_args[0][0]
        assert '--fix' not in cmd

    @pytest.mark.asyncio
    async def test_usage_error_raises_exception(self, mocker):
        """Exit code 2 (usage error) raises exception."""
        mock_run = mocker.patch('subprocess.run')
        mock_run.return_value = MagicMock(
            returncode=2,
            stdout='',
            stderr='error: missing required argument',
        )
        mocker.patch('shutil.which', return_value='/usr/bin/dsql-lint')

        with pytest.raises(Exception, match='usage error'):
            await dsql_lint('SELECT 1;', fix=False)

    @pytest.mark.asyncio
    async def test_timeout_raises_exception(self, mocker):
        """Timeout raises exception."""
        import subprocess
        mock_run = mocker.patch('subprocess.run')
        mock_run.side_effect = subprocess.TimeoutExpired(cmd='dsql-lint', timeout=30)
        mocker.patch('shutil.which', return_value='/usr/bin/dsql-lint')

        with pytest.raises(Exception, match='timed out'):
            await dsql_lint('SELECT 1;', fix=False)

    @pytest.mark.asyncio
    async def test_invalid_json_raises_exception(self, mocker):
        """Invalid JSON output raises exception."""
        mock_run = mocker.patch('subprocess.run')
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout='not valid json{{{',
            stderr='',
        )
        mocker.patch('shutil.which', return_value='/usr/bin/dsql-lint')

        with pytest.raises(Exception, match='invalid JSON'):
            await dsql_lint('SELECT 1;', fix=False)

    @pytest.mark.asyncio
    async def test_empty_files_array(self, mocker):
        """Empty files array returns empty diagnostics."""
        mock_output = json.dumps({
            'schema_version': 1,
            'files': [],
            'summary': {'errors': 0, 'warnings': 0, 'fixed': 0},
        })

        mock_run = mocker.patch('subprocess.run')
        mock_run.return_value = MagicMock(returncode=0, stdout=mock_output, stderr='')
        mocker.patch('shutil.which', return_value='/usr/bin/dsql-lint')

        result = await dsql_lint('SELECT 1;', fix=False)

        assert result['diagnostics'] == []
        assert result['fixed_sql'] is None

    @pytest.mark.asyncio
    async def test_file_not_found_error_raises_exception(self, mocker):
        """FileNotFoundError from subprocess raises exception."""
        mock_run = mocker.patch('subprocess.run')
        mock_run.side_effect = FileNotFoundError('No such file or directory')
        mocker.patch('shutil.which', return_value='/usr/bin/dsql-lint')

        with pytest.raises(Exception, match='dsql-lint binary not found'):
            await dsql_lint('SELECT 1;', fix=False)

    @pytest.mark.asyncio
    async def test_empty_stdout_raises_exception(self, mocker):
        """Empty stdout from dsql-lint raises exception."""
        mock_run = mocker.patch('subprocess.run')
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout='',
            stderr='some error',
        )
        mocker.patch('shutil.which', return_value='/usr/bin/dsql-lint')

        with pytest.raises(Exception, match='dsql-lint produced no output'):
            await dsql_lint('SELECT 1;', fix=False)
