[project]
name = "mcp-waf"
version = "0.1.0"
description = "AWS WAF MCP server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.37.35",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
