# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-generated enum types from botocore service model.

DO NOT EDIT — regenerate with: python src/codegen/generate.py mediapackagev2
Generated from: mediapackagev2 2022-12-25
Botocore version: 1.40.49
"""

from enum import Enum


class AdMarkerDash(str, Enum):
    """Ad Marker Dash."""

    BINARY = 'BINARY'
    XML = 'XML'


class AdMarkerHls(str, Enum):
    """Ad Marker Hls."""

    DATERANGE = 'DATERANGE'
    SCTE35_ENHANCED = 'SCTE35_ENHANCED'


class CmafEncryptionMethod(str, Enum):
    """Cmaf Encryption Method."""

    CENC = 'CENC'
    CBCS = 'CBCS'


class ConflictExceptionType(str, Enum):
    """Conflict Exception Type."""

    RESOURCE_IN_USE = 'RESOURCE_IN_USE'
    RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS'
    IDEMPOTENT_PARAMETER_MISMATCH = 'IDEMPOTENT_PARAMETER_MISMATCH'
    CONFLICTING_OPERATION = 'CONFLICTING_OPERATION'


class ContainerType(str, Enum):
    """Container Type."""

    TS = 'TS'
    CMAF = 'CMAF'
    ISM = 'ISM'


class DashCompactness(str, Enum):
    """Dash Compactness."""

    STANDARD = 'STANDARD'
    NONE = 'NONE'


class DashDrmSignaling(str, Enum):
    """Dash Drm Signaling."""

    INDIVIDUAL = 'INDIVIDUAL'
    REFERENCED = 'REFERENCED'


class DashPeriodTrigger(str, Enum):
    """Dash Period Trigger."""

    AVAILS = 'AVAILS'
    DRM_KEY_ROTATION = 'DRM_KEY_ROTATION'
    SOURCE_CHANGES = 'SOURCE_CHANGES'
    SOURCE_DISRUPTIONS = 'SOURCE_DISRUPTIONS'
    NONE = 'NONE'


class DashProfile(str, Enum):
    """Dash Profile."""

    DVB_DASH = 'DVB_DASH'


class DashSegmentTemplateFormat(str, Enum):
    """Dash Segment Template Format."""

    NUMBER_WITH_TIMELINE = 'NUMBER_WITH_TIMELINE'


class DashTtmlProfile(str, Enum):
    """Dash Ttml Profile."""

    IMSC_1 = 'IMSC_1'
    EBU_TT_D_101 = 'EBU_TT_D_101'


class DashUtcTimingMode(str, Enum):
    """Dash Utc Timing Mode."""

    HTTP_HEAD = 'HTTP_HEAD'
    HTTP_ISO = 'HTTP_ISO'
    HTTP_XSDATE = 'HTTP_XSDATE'
    UTC_DIRECT = 'UTC_DIRECT'


class DrmSystem(str, Enum):
    """Drm System."""

    CLEAR_KEY_AES_128 = 'CLEAR_KEY_AES_128'
    FAIRPLAY = 'FAIRPLAY'
    PLAYREADY = 'PLAYREADY'
    WIDEVINE = 'WIDEVINE'
    IRDETO = 'IRDETO'


class EndpointErrorCondition(str, Enum):
    """Endpoint Error Condition."""

    STALE_MANIFEST = 'STALE_MANIFEST'
    INCOMPLETE_MANIFEST = 'INCOMPLETE_MANIFEST'
    MISSING_DRM_KEY = 'MISSING_DRM_KEY'
    SLATE_INPUT = 'SLATE_INPUT'


class HarvestJobStatus(str, Enum):
    """Harvest Job Status."""

    QUEUED = 'QUEUED'
    IN_PROGRESS = 'IN_PROGRESS'
    CANCELLED = 'CANCELLED'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'


class InputType(str, Enum):
    """Input Type."""

    HLS = 'HLS'
    CMAF = 'CMAF'


class IsmEncryptionMethod(str, Enum):
    """Ism Encryption Method."""

    CENC = 'CENC'


class MssManifestLayout(str, Enum):
    """Mss Manifest Layout."""

    FULL = 'FULL'
    COMPACT = 'COMPACT'


class PresetSpeke20Audio(str, Enum):
    """Preset Speke20Audio."""

    PRESET_AUDIO_1 = 'PRESET_AUDIO_1'
    PRESET_AUDIO_2 = 'PRESET_AUDIO_2'
    PRESET_AUDIO_3 = 'PRESET_AUDIO_3'
    SHARED = 'SHARED'
    UNENCRYPTED = 'UNENCRYPTED'


class PresetSpeke20Video(str, Enum):
    """Preset Speke20Video."""

    PRESET_VIDEO_1 = 'PRESET_VIDEO_1'
    PRESET_VIDEO_2 = 'PRESET_VIDEO_2'
    PRESET_VIDEO_3 = 'PRESET_VIDEO_3'
    PRESET_VIDEO_4 = 'PRESET_VIDEO_4'
    PRESET_VIDEO_5 = 'PRESET_VIDEO_5'
    PRESET_VIDEO_6 = 'PRESET_VIDEO_6'
    PRESET_VIDEO_7 = 'PRESET_VIDEO_7'
    PRESET_VIDEO_8 = 'PRESET_VIDEO_8'
    SHARED = 'SHARED'
    UNENCRYPTED = 'UNENCRYPTED'


class ResourceTypeNotFound(str, Enum):
    """Resource Type Not Found."""

    CHANNEL_GROUP = 'CHANNEL_GROUP'
    CHANNEL = 'CHANNEL'
    ORIGIN_ENDPOINT = 'ORIGIN_ENDPOINT'
    HARVEST_JOB = 'HARVEST_JOB'


class ScteFilter(str, Enum):
    """Scte Filter."""

    SPLICE_INSERT = 'SPLICE_INSERT'
    BREAK = 'BREAK'
    PROVIDER_ADVERTISEMENT = 'PROVIDER_ADVERTISEMENT'
    DISTRIBUTOR_ADVERTISEMENT = 'DISTRIBUTOR_ADVERTISEMENT'
    PROVIDER_PLACEMENT_OPPORTUNITY = 'PROVIDER_PLACEMENT_OPPORTUNITY'
    DISTRIBUTOR_PLACEMENT_OPPORTUNITY = 'DISTRIBUTOR_PLACEMENT_OPPORTUNITY'
    PROVIDER_OVERLAY_PLACEMENT_OPPORTUNITY = 'PROVIDER_OVERLAY_PLACEMENT_OPPORTUNITY'
    DISTRIBUTOR_OVERLAY_PLACEMENT_OPPORTUNITY = 'DISTRIBUTOR_OVERLAY_PLACEMENT_OPPORTUNITY'
    PROGRAM = 'PROGRAM'


class TsEncryptionMethod(str, Enum):
    """Ts Encryption Method."""

    AES_128 = 'AES_128'
    SAMPLE_AES = 'SAMPLE_AES'


class ValidationExceptionType(str, Enum):
    """Validation Exception Type."""

    CONTAINER_TYPE_IMMUTABLE = 'CONTAINER_TYPE_IMMUTABLE'
    INVALID_PAGINATION_TOKEN = 'INVALID_PAGINATION_TOKEN'
    INVALID_PAGINATION_MAX_RESULTS = 'INVALID_PAGINATION_MAX_RESULTS'
    INVALID_POLICY = 'INVALID_POLICY'
    INVALID_ROLE_ARN = 'INVALID_ROLE_ARN'
    MANIFEST_NAME_COLLISION = 'MANIFEST_NAME_COLLISION'
    ENCRYPTION_METHOD_CONTAINER_TYPE_MISMATCH = 'ENCRYPTION_METHOD_CONTAINER_TYPE_MISMATCH'
    CENC_IV_INCOMPATIBLE = 'CENC_IV_INCOMPATIBLE'
    ENCRYPTION_CONTRACT_WITHOUT_AUDIO_RENDITION_INCOMPATIBLE = (
        'ENCRYPTION_CONTRACT_WITHOUT_AUDIO_RENDITION_INCOMPATIBLE'
    )
    ENCRYPTION_CONTRACT_WITH_ISM_CONTAINER_INCOMPATIBLE = (
        'ENCRYPTION_CONTRACT_WITH_ISM_CONTAINER_INCOMPATIBLE'
    )
    ENCRYPTION_CONTRACT_UNENCRYPTED = 'ENCRYPTION_CONTRACT_UNENCRYPTED'
    ENCRYPTION_CONTRACT_SHARED = 'ENCRYPTION_CONTRACT_SHARED'
    NUM_MANIFESTS_LOW = 'NUM_MANIFESTS_LOW'
    NUM_MANIFESTS_HIGH = 'NUM_MANIFESTS_HIGH'
    MANIFEST_DRM_SYSTEMS_INCOMPATIBLE = 'MANIFEST_DRM_SYSTEMS_INCOMPATIBLE'
    DRM_SYSTEMS_ENCRYPTION_METHOD_INCOMPATIBLE = 'DRM_SYSTEMS_ENCRYPTION_METHOD_INCOMPATIBLE'
    ROLE_ARN_NOT_ASSUMABLE = 'ROLE_ARN_NOT_ASSUMABLE'
    ROLE_ARN_LENGTH_OUT_OF_RANGE = 'ROLE_ARN_LENGTH_OUT_OF_RANGE'
    ROLE_ARN_INVALID_FORMAT = 'ROLE_ARN_INVALID_FORMAT'
    URL_INVALID = 'URL_INVALID'
    URL_SCHEME = 'URL_SCHEME'
    URL_USER_INFO = 'URL_USER_INFO'
    URL_PORT = 'URL_PORT'
    URL_UNKNOWN_HOST = 'URL_UNKNOWN_HOST'
    URL_LOCAL_ADDRESS = 'URL_LOCAL_ADDRESS'
    URL_LOOPBACK_ADDRESS = 'URL_LOOPBACK_ADDRESS'
    URL_LINK_LOCAL_ADDRESS = 'URL_LINK_LOCAL_ADDRESS'
    URL_MULTICAST_ADDRESS = 'URL_MULTICAST_ADDRESS'
    MEMBER_INVALID = 'MEMBER_INVALID'
    MEMBER_MISSING = 'MEMBER_MISSING'
    MEMBER_MIN_VALUE = 'MEMBER_MIN_VALUE'
    MEMBER_MAX_VALUE = 'MEMBER_MAX_VALUE'
    MEMBER_MIN_LENGTH = 'MEMBER_MIN_LENGTH'
    MEMBER_MAX_LENGTH = 'MEMBER_MAX_LENGTH'
    MEMBER_INVALID_ENUM_VALUE = 'MEMBER_INVALID_ENUM_VALUE'
    MEMBER_DOES_NOT_MATCH_PATTERN = 'MEMBER_DOES_NOT_MATCH_PATTERN'
    INVALID_MANIFEST_FILTER = 'INVALID_MANIFEST_FILTER'
    INVALID_TIME_DELAY_SECONDS = 'INVALID_TIME_DELAY_SECONDS'
    END_TIME_EARLIER_THAN_START_TIME = 'END_TIME_EARLIER_THAN_START_TIME'
    TS_CONTAINER_TYPE_WITH_DASH_MANIFEST = 'TS_CONTAINER_TYPE_WITH_DASH_MANIFEST'
    DIRECT_MODE_WITH_TIMING_SOURCE = 'DIRECT_MODE_WITH_TIMING_SOURCE'
    NONE_MODE_WITH_TIMING_SOURCE = 'NONE_MODE_WITH_TIMING_SOURCE'
    TIMING_SOURCE_MISSING = 'TIMING_SOURCE_MISSING'
    UPDATE_PERIOD_SMALLER_THAN_SEGMENT_DURATION = 'UPDATE_PERIOD_SMALLER_THAN_SEGMENT_DURATION'
    PERIOD_TRIGGERS_NONE_SPECIFIED_WITH_ADDITIONAL_VALUES = (
        'PERIOD_TRIGGERS_NONE_SPECIFIED_WITH_ADDITIONAL_VALUES'
    )
    DRM_SIGNALING_MISMATCH_SEGMENT_ENCRYPTION_STATUS = (
        'DRM_SIGNALING_MISMATCH_SEGMENT_ENCRYPTION_STATUS'
    )
    ONLY_CMAF_INPUT_TYPE_ALLOW_FORCE_ENDPOINT_ERROR_CONFIGURATION = (
        'ONLY_CMAF_INPUT_TYPE_ALLOW_FORCE_ENDPOINT_ERROR_CONFIGURATION'
    )
    SOURCE_DISRUPTIONS_ENABLED_INCORRECTLY = 'SOURCE_DISRUPTIONS_ENABLED_INCORRECTLY'
    HARVESTED_MANIFEST_HAS_START_END_FILTER_CONFIGURATION = (
        'HARVESTED_MANIFEST_HAS_START_END_FILTER_CONFIGURATION'
    )
    HARVESTED_MANIFEST_NOT_FOUND_ON_ENDPOINT = 'HARVESTED_MANIFEST_NOT_FOUND_ON_ENDPOINT'
    TOO_MANY_IN_PROGRESS_HARVEST_JOBS = 'TOO_MANY_IN_PROGRESS_HARVEST_JOBS'
    HARVEST_JOB_INELIGIBLE_FOR_CANCELLATION = 'HARVEST_JOB_INELIGIBLE_FOR_CANCELLATION'
    INVALID_HARVEST_JOB_DURATION = 'INVALID_HARVEST_JOB_DURATION'
    HARVEST_JOB_S3_DESTINATION_MISSING_OR_INCOMPLETE = (
        'HARVEST_JOB_S3_DESTINATION_MISSING_OR_INCOMPLETE'
    )
    HARVEST_JOB_UNABLE_TO_WRITE_TO_S3_DESTINATION = 'HARVEST_JOB_UNABLE_TO_WRITE_TO_S3_DESTINATION'
    HARVEST_JOB_CUSTOMER_ENDPOINT_READ_ACCESS_DENIED = (
        'HARVEST_JOB_CUSTOMER_ENDPOINT_READ_ACCESS_DENIED'
    )
    CLIP_START_TIME_WITH_START_OR_END = 'CLIP_START_TIME_WITH_START_OR_END'
    START_TAG_TIME_OFFSET_INVALID = 'START_TAG_TIME_OFFSET_INVALID'
    INCOMPATIBLE_DASH_PROFILE_DVB_DASH_CONFIGURATION = (
        'INCOMPATIBLE_DASH_PROFILE_DVB_DASH_CONFIGURATION'
    )
    DASH_DVB_ATTRIBUTES_WITHOUT_DVB_DASH_PROFILE = 'DASH_DVB_ATTRIBUTES_WITHOUT_DVB_DASH_PROFILE'
    INCOMPATIBLE_DASH_COMPACTNESS_CONFIGURATION = 'INCOMPATIBLE_DASH_COMPACTNESS_CONFIGURATION'
    INCOMPATIBLE_XML_ENCODING = 'INCOMPATIBLE_XML_ENCODING'
    CMAF_EXCLUDE_SEGMENT_DRM_METADATA_INCOMPATIBLE_CONTAINER_TYPE = (
        'CMAF_EXCLUDE_SEGMENT_DRM_METADATA_INCOMPATIBLE_CONTAINER_TYPE'
    )
    ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_INPUT_SWITCHING = (
        'ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_INPUT_SWITCHING'
    )
    ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_OUTPUT_CONFIGURATION = (
        'ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_OUTPUT_CONFIGURATION'
    )
    ONLY_CMAF_INPUT_TYPE_ALLOW_PREFERRED_INPUT_CONFIGURATION = (
        'ONLY_CMAF_INPUT_TYPE_ALLOW_PREFERRED_INPUT_CONFIGURATION'
    )
    TS_CONTAINER_TYPE_WITH_MSS_MANIFEST = 'TS_CONTAINER_TYPE_WITH_MSS_MANIFEST'
    CMAF_CONTAINER_TYPE_WITH_MSS_MANIFEST = 'CMAF_CONTAINER_TYPE_WITH_MSS_MANIFEST'
    ISM_CONTAINER_TYPE_WITH_HLS_MANIFEST = 'ISM_CONTAINER_TYPE_WITH_HLS_MANIFEST'
    ISM_CONTAINER_TYPE_WITH_LL_HLS_MANIFEST = 'ISM_CONTAINER_TYPE_WITH_LL_HLS_MANIFEST'
    ISM_CONTAINER_TYPE_WITH_DASH_MANIFEST = 'ISM_CONTAINER_TYPE_WITH_DASH_MANIFEST'
    ISM_CONTAINER_TYPE_WITH_SCTE = 'ISM_CONTAINER_TYPE_WITH_SCTE'
    ISM_CONTAINER_WITH_KEY_ROTATION = 'ISM_CONTAINER_WITH_KEY_ROTATION'
    BATCH_GET_SECRET_VALUE_DENIED = 'BATCH_GET_SECRET_VALUE_DENIED'  # pragma: allowlist secret
    GET_SECRET_VALUE_DENIED = 'GET_SECRET_VALUE_DENIED'  # pragma: allowlist secret
    DESCRIBE_SECRET_DENIED = 'DESCRIBE_SECRET_DENIED'  # pragma: allowlist secret
    INVALID_SECRET_FORMAT = 'INVALID_SECRET_FORMAT'  # pragma: allowlist secret
    SECRET_IS_NOT_ONE_KEY_VALUE_PAIR = (
        'SECRET_IS_NOT_ONE_KEY_VALUE_PAIR'  # pragma: allowlist secret
    )
    INVALID_SECRET_KEY = 'INVALID_SECRET_KEY'  # pragma: allowlist secret
    INVALID_SECRET_VALUE = 'INVALID_SECRET_VALUE'  # pragma: allowlist secret
    SECRET_ARN_RESOURCE_NOT_FOUND = 'SECRET_ARN_RESOURCE_NOT_FOUND'  # pragma: allowlist secret
    DECRYPT_SECRET_FAILED = 'DECRYPT_SECRET_FAILED'  # pragma: allowlist secret
    TOO_MANY_SECRETS = 'TOO_MANY_SECRETS'  # pragma: allowlist secret
    DUPLICATED_SECRET = 'DUPLICATED_SECRET'  # pragma: allowlist secret
    MALFORMED_SECRET_ARN = 'MALFORMED_SECRET_ARN'  # pragma: allowlist secret
    SECRET_FROM_DIFFERENT_ACCOUNT = 'SECRET_FROM_DIFFERENT_ACCOUNT'  # pragma: allowlist secret
    SECRET_FROM_DIFFERENT_REGION = 'SECRET_FROM_DIFFERENT_REGION'  # pragma: allowlist secret
    INVALID_SECRET = 'INVALID_SECRET'  # pragma: allowlist secret
