# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Auto-generated operations metadata from botocore service model.

DO NOT EDIT — regenerate with: python src/codegen/generate.py mediapackagev2
"""

from awslabs.amazon_mediapackagev2_mcp_server.models import (
    CancelHarvestJobRequest,
    CancelHarvestJobResponse,
    CreateChannelGroupRequest,
    CreateChannelGroupResponse,
    CreateChannelRequest,
    CreateChannelResponse,
    CreateHarvestJobRequest,
    CreateHarvestJobResponse,
    CreateOriginEndpointRequest,
    CreateOriginEndpointResponse,
    DeleteChannelGroupRequest,
    DeleteChannelGroupResponse,
    DeleteChannelPolicyRequest,
    DeleteChannelPolicyResponse,
    DeleteChannelRequest,
    DeleteChannelResponse,
    DeleteOriginEndpointPolicyRequest,
    DeleteOriginEndpointPolicyResponse,
    DeleteOriginEndpointRequest,
    DeleteOriginEndpointResponse,
    GetChannelGroupRequest,
    GetChannelGroupResponse,
    GetChannelPolicyRequest,
    GetChannelPolicyResponse,
    GetChannelRequest,
    GetChannelResponse,
    GetHarvestJobRequest,
    GetHarvestJobResponse,
    GetOriginEndpointPolicyRequest,
    GetOriginEndpointPolicyResponse,
    GetOriginEndpointRequest,
    GetOriginEndpointResponse,
    ListChannelGroupsRequest,
    ListChannelGroupsResponse,
    ListChannelsRequest,
    ListChannelsResponse,
    ListHarvestJobsRequest,
    ListHarvestJobsResponse,
    ListOriginEndpointsRequest,
    ListOriginEndpointsResponse,
    ListTagsForResourceRequest,
    ListTagsForResourceResponse,
    PutChannelPolicyRequest,
    PutChannelPolicyResponse,
    PutOriginEndpointPolicyRequest,
    PutOriginEndpointPolicyResponse,
    ResetChannelStateRequest,
    ResetChannelStateResponse,
    ResetOriginEndpointStateRequest,
    ResetOriginEndpointStateResponse,
    TagResourceRequest,
    UntagResourceRequest,
    UpdateChannelGroupRequest,
    UpdateChannelGroupResponse,
    UpdateChannelRequest,
    UpdateChannelResponse,
    UpdateOriginEndpointRequest,
    UpdateOriginEndpointResponse,
)


OPERATIONS = {
    'CancelHarvestJob': {
        'name': 'CancelHarvestJob',
        'tool_name': 'cancel_harvest_job',
        'input_model': CancelHarvestJobRequest,
        'output_model': CancelHarvestJobResponse,
        'http_method': 'PUT',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint/{OriginEndpointName}/harvestJob/{HarvestJobName}',
        'auto_description': 'Cancels an in-progress harvest job.',
        'pagination': None,
    },
    'CreateChannel': {
        'name': 'CreateChannel',
        'tool_name': 'create_channel',
        'input_model': CreateChannelRequest,
        'output_model': CreateChannelResponse,
        'http_method': 'POST',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel',
        'auto_description': 'Create a channel to start receiving content streams. The channel represents the input to MediaPackage for incoming live content from an encoder such as AWS Elemental MediaLive. The channel receives content, and after packaging it, outputs it through an origin endpoint to downstream devices (such as video players or CDNs) that request the content. You can create only one channel with each request. We recommend that you spread out channels between channel groups, such as putting redundant channels in the same AWS Region in different channel groups.',
        'pagination': None,
    },
    'CreateChannelGroup': {
        'name': 'CreateChannelGroup',
        'tool_name': 'create_channel_group',
        'input_model': CreateChannelGroupRequest,
        'output_model': CreateChannelGroupResponse,
        'http_method': 'POST',
        'request_uri': '/channelGroup',
        'auto_description': 'Create a channel group to group your channels and origin endpoints. A channel group is the top-level resource that consists of channels and origin endpoints that are associated with it and that provides predictable URLs for stream delivery. All channels and origin endpoints within the channel group are guaranteed to share the DNS. You can create only one channel group with each request.',
        'pagination': None,
    },
    'CreateHarvestJob': {
        'name': 'CreateHarvestJob',
        'tool_name': 'create_harvest_job',
        'input_model': CreateHarvestJobRequest,
        'output_model': CreateHarvestJobResponse,
        'http_method': 'POST',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint/{OriginEndpointName}/harvestJob',
        'auto_description': 'Creates a new harvest job to export content from a MediaPackage v2 channel to an S3 bucket.',
        'pagination': None,
    },
    'CreateOriginEndpoint': {
        'name': 'CreateOriginEndpoint',
        'tool_name': 'create_origin_endpoint',
        'input_model': CreateOriginEndpointRequest,
        'output_model': CreateOriginEndpointResponse,
        'http_method': 'POST',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint',
        'auto_description': 'The endpoint is attached to a channel, and represents the output of the live content. You can associate multiple endpoints to a single channel. Each endpoint gives players and downstream CDNs (such as Amazon CloudFront) access to the content for playback. Content can\u0027t be served from a channel until it has an endpoint. You can create only one endpoint with each request.',
        'pagination': None,
    },
    'DeleteChannel': {
        'name': 'DeleteChannel',
        'tool_name': 'delete_channel',
        'input_model': DeleteChannelRequest,
        'output_model': DeleteChannelResponse,
        'http_method': 'DELETE',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/',
        'auto_description': 'Delete a channel to stop AWS Elemental MediaPackage from receiving further content. You must delete the channel\u0027s origin endpoints before you can delete the channel.',
        'pagination': None,
    },
    'DeleteChannelGroup': {
        'name': 'DeleteChannelGroup',
        'tool_name': 'delete_channel_group',
        'input_model': DeleteChannelGroupRequest,
        'output_model': DeleteChannelGroupResponse,
        'http_method': 'DELETE',
        'request_uri': '/channelGroup/{ChannelGroupName}',
        'auto_description': 'Delete a channel group. You must delete the channel group\u0027s channels and origin endpoints before you can delete the channel group. If you delete a channel group, you\u0027ll lose access to the egress domain and will have to create a new channel group to replace it.',
        'pagination': None,
    },
    'DeleteChannelPolicy': {
        'name': 'DeleteChannelPolicy',
        'tool_name': 'delete_channel_policy',
        'input_model': DeleteChannelPolicyRequest,
        'output_model': DeleteChannelPolicyResponse,
        'http_method': 'DELETE',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/policy',
        'auto_description': 'Delete a channel policy.',
        'pagination': None,
    },
    'DeleteOriginEndpoint': {
        'name': 'DeleteOriginEndpoint',
        'tool_name': 'delete_origin_endpoint',
        'input_model': DeleteOriginEndpointRequest,
        'output_model': DeleteOriginEndpointResponse,
        'http_method': 'DELETE',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint/{OriginEndpointName}',
        'auto_description': 'Origin endpoints can serve content until they\u0027re deleted. Delete the endpoint if it should no longer respond to playback requests. You must delete all endpoints from a channel before you can delete the channel.',
        'pagination': None,
    },
    'DeleteOriginEndpointPolicy': {
        'name': 'DeleteOriginEndpointPolicy',
        'tool_name': 'delete_origin_endpoint_policy',
        'input_model': DeleteOriginEndpointPolicyRequest,
        'output_model': DeleteOriginEndpointPolicyResponse,
        'http_method': 'DELETE',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint/{OriginEndpointName}/policy',
        'auto_description': 'Delete an origin endpoint policy.',
        'pagination': None,
    },
    'GetChannel': {
        'name': 'GetChannel',
        'tool_name': 'get_channel',
        'input_model': GetChannelRequest,
        'output_model': GetChannelResponse,
        'http_method': 'GET',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/',
        'auto_description': 'Retrieves the specified channel that\u0027s configured in AWS Elemental MediaPackage.',
        'pagination': None,
    },
    'GetChannelGroup': {
        'name': 'GetChannelGroup',
        'tool_name': 'get_channel_group',
        'input_model': GetChannelGroupRequest,
        'output_model': GetChannelGroupResponse,
        'http_method': 'GET',
        'request_uri': '/channelGroup/{ChannelGroupName}',
        'auto_description': 'Retrieves the specified channel group that\u0027s configured in AWS Elemental MediaPackage.',
        'pagination': None,
    },
    'GetChannelPolicy': {
        'name': 'GetChannelPolicy',
        'tool_name': 'get_channel_policy',
        'input_model': GetChannelPolicyRequest,
        'output_model': GetChannelPolicyResponse,
        'http_method': 'GET',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/policy',
        'auto_description': 'Retrieves the specified channel policy that\u0027s configured in AWS Elemental MediaPackage. With policies, you can specify who has access to AWS resources and what actions they can perform on those resources.',
        'pagination': None,
    },
    'GetHarvestJob': {
        'name': 'GetHarvestJob',
        'tool_name': 'get_harvest_job',
        'input_model': GetHarvestJobRequest,
        'output_model': GetHarvestJobResponse,
        'http_method': 'GET',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint/{OriginEndpointName}/harvestJob/{HarvestJobName}',
        'auto_description': 'Retrieves the details of a specific harvest job.',
        'pagination': None,
    },
    'GetOriginEndpoint': {
        'name': 'GetOriginEndpoint',
        'tool_name': 'get_origin_endpoint',
        'input_model': GetOriginEndpointRequest,
        'output_model': GetOriginEndpointResponse,
        'http_method': 'GET',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint/{OriginEndpointName}',
        'auto_description': 'Retrieves the specified origin endpoint that\u0027s configured in AWS Elemental MediaPackage to obtain its playback URL and to view the packaging settings that it\u0027s currently using.',
        'pagination': None,
    },
    'GetOriginEndpointPolicy': {
        'name': 'GetOriginEndpointPolicy',
        'tool_name': 'get_origin_endpoint_policy',
        'input_model': GetOriginEndpointPolicyRequest,
        'output_model': GetOriginEndpointPolicyResponse,
        'http_method': 'GET',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint/{OriginEndpointName}/policy',
        'auto_description': 'Retrieves the specified origin endpoint policy that\u0027s configured in AWS Elemental MediaPackage.',
        'pagination': None,
    },
    'ListChannelGroups': {
        'name': 'ListChannelGroups',
        'tool_name': 'list_channel_groups',
        'input_model': ListChannelGroupsRequest,
        'output_model': ListChannelGroupsResponse,
        'http_method': 'GET',
        'request_uri': '/channelGroup',
        'auto_description': 'Retrieves all channel groups that are configured in Elemental MediaPackage.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['Items'],
            'limit_key': 'MaxResults',
        },
    },
    'ListChannels': {
        'name': 'ListChannels',
        'tool_name': 'list_channels',
        'input_model': ListChannelsRequest,
        'output_model': ListChannelsResponse,
        'http_method': 'GET',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel',
        'auto_description': 'Retrieves all channels in a specific channel group that are configured in AWS Elemental MediaPackage.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['Items'],
            'limit_key': 'MaxResults',
        },
    },
    'ListHarvestJobs': {
        'name': 'ListHarvestJobs',
        'tool_name': 'list_harvest_jobs',
        'input_model': ListHarvestJobsRequest,
        'output_model': ListHarvestJobsResponse,
        'http_method': 'GET',
        'request_uri': '/channelGroup/{ChannelGroupName}/harvestJob',
        'auto_description': 'Retrieves a list of harvest jobs that match the specified criteria.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['Items'],
            'limit_key': 'MaxResults',
        },
    },
    'ListOriginEndpoints': {
        'name': 'ListOriginEndpoints',
        'tool_name': 'list_origin_endpoints',
        'input_model': ListOriginEndpointsRequest,
        'output_model': ListOriginEndpointsResponse,
        'http_method': 'GET',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint',
        'auto_description': 'Retrieves all origin endpoints in a specific channel that are configured in AWS Elemental MediaPackage.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['Items'],
            'limit_key': 'MaxResults',
        },
    },
    'ListTagsForResource': {
        'name': 'ListTagsForResource',
        'tool_name': 'list_tags_for_resource',
        'input_model': ListTagsForResourceRequest,
        'output_model': ListTagsForResourceResponse,
        'http_method': 'GET',
        'request_uri': '/tags/{ResourceArn}',
        'auto_description': 'Lists the tags assigned to a resource.',
        'pagination': None,
    },
    'PutChannelPolicy': {
        'name': 'PutChannelPolicy',
        'tool_name': 'put_channel_policy',
        'input_model': PutChannelPolicyRequest,
        'output_model': PutChannelPolicyResponse,
        'http_method': 'PUT',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/policy',
        'auto_description': 'Attaches an IAM policy to the specified channel. With policies, you can specify who has access to AWS resources and what actions they can perform on those resources. You can attach only one policy with each request.',
        'pagination': None,
    },
    'PutOriginEndpointPolicy': {
        'name': 'PutOriginEndpointPolicy',
        'tool_name': 'put_origin_endpoint_policy',
        'input_model': PutOriginEndpointPolicyRequest,
        'output_model': PutOriginEndpointPolicyResponse,
        'http_method': 'POST',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint/{OriginEndpointName}/policy',
        'auto_description': 'Attaches an IAM policy to the specified origin endpoint. You can attach only one policy with each request.',
        'pagination': None,
    },
    'ResetChannelState': {
        'name': 'ResetChannelState',
        'tool_name': 'reset_channel_state',
        'input_model': ResetChannelStateRequest,
        'output_model': ResetChannelStateResponse,
        'http_method': 'POST',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/reset',
        'auto_description': 'Resetting the channel can help to clear errors from misconfigurations in the encoder. A reset refreshes the ingest stream and removes previous content. Be sure to stop the encoder before you reset the channel, and wait at least 30 seconds before you restart the encoder.',
        'pagination': None,
    },
    'ResetOriginEndpointState': {
        'name': 'ResetOriginEndpointState',
        'tool_name': 'reset_origin_endpoint_state',
        'input_model': ResetOriginEndpointStateRequest,
        'output_model': ResetOriginEndpointStateResponse,
        'http_method': 'POST',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint/{OriginEndpointName}/reset',
        'auto_description': 'Resetting the origin endpoint can help to resolve unexpected behavior and other content packaging issues. It also helps to preserve special events when you don\u0027t want the previous content to be available for viewing. A reset clears out all previous content from the origin endpoint. MediaPackage might return old content from this endpoint in the first 30 seconds after the endpoint reset. For best results, when possible, wait 30 seconds from endpoint reset to send playback requests to this endpoint.',
        'pagination': None,
    },
    'TagResource': {
        'name': 'TagResource',
        'tool_name': 'tag_resource',
        'input_model': TagResourceRequest,
        'output_model': dict,
        'http_method': 'POST',
        'request_uri': '/tags/{ResourceArn}',
        'auto_description': 'Assigns one of more tags (key-value pairs) to the specified MediaPackage resource. Tags can help you organize and categorize your resources. You can also use them to scope user permissions, by granting a user permission to access or change only resources with certain tag values. You can use the TagResource operation with a resource that already has tags. If you specify a new tag key for the resource, this tag is appended to the list of tags associated with the resource. If you specify a tag key that is already associated with the resource, the new tag value that you specify replaces the previous value for that tag.',
        'pagination': None,
    },
    'UntagResource': {
        'name': 'UntagResource',
        'tool_name': 'untag_resource',
        'input_model': UntagResourceRequest,
        'output_model': dict,
        'http_method': 'DELETE',
        'request_uri': '/tags/{ResourceArn}',
        'auto_description': 'Removes one or more tags from the specified resource.',
        'pagination': None,
    },
    'UpdateChannel': {
        'name': 'UpdateChannel',
        'tool_name': 'update_channel',
        'input_model': UpdateChannelRequest,
        'output_model': UpdateChannelResponse,
        'http_method': 'PUT',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/',
        'auto_description': 'Update the specified channel. You can edit if MediaPackage sends ingest or egress access logs to the CloudWatch log group, if content will be encrypted, the description on a channel, and your channel\u0027s policy settings. You can\u0027t edit the name of the channel or CloudFront distribution details. Any edits you make that impact the video output may not be reflected for a few minutes.',
        'pagination': None,
    },
    'UpdateChannelGroup': {
        'name': 'UpdateChannelGroup',
        'tool_name': 'update_channel_group',
        'input_model': UpdateChannelGroupRequest,
        'output_model': UpdateChannelGroupResponse,
        'http_method': 'PUT',
        'request_uri': '/channelGroup/{ChannelGroupName}',
        'auto_description': 'Update the specified channel group. You can edit the description on a channel group for easier identification later from the AWS Elemental MediaPackage console. You can\u0027t edit the name of the channel group. Any edits you make that impact the video output may not be reflected for a few minutes.',
        'pagination': None,
    },
    'UpdateOriginEndpoint': {
        'name': 'UpdateOriginEndpoint',
        'tool_name': 'update_origin_endpoint',
        'input_model': UpdateOriginEndpointRequest,
        'output_model': UpdateOriginEndpointResponse,
        'http_method': 'PUT',
        'request_uri': '/channelGroup/{ChannelGroupName}/channel/{ChannelName}/originEndpoint/{OriginEndpointName}',
        'auto_description': 'Update the specified origin endpoint. Edit the packaging preferences on an endpoint to optimize the viewing experience. You can\u0027t edit the name of the endpoint. Any edits you make that impact the video output may not be reflected for a few minutes.',
        'pagination': None,
    },
}
