site_name: AWS MCP Servers
site_url: https://awslabs.github.io/mcp

repo_name: 'awslabs/mcp'
repo_url: 'https://github.com/awslabs/mcp'
copyright: '&copy; Amazon Web Services, Inc. or its affiliates. All rights reserved.'

theme:
  name: material
  logo: images/logo.png
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
  palette:
    # Palette toggle for light mode
    - scheme: dracula
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - privacy
  - search
  - include-markdown
nav:
  - Home: index.md
  - AWS MCP Servers:
    - Core MCP Server: servers/core-mcp-server.md
    - Amazon EKS: 
    - Amazon Bedrock Knowledge Base Retrieval: servers/bedrock-kb-retrieval-mcp-server.md
    - AWS CDK: servers/cdk-mcp-server.md
    - Cost Analysis: servers/cost-analysis-mcp-server.md
    - Amazon Nova Canvas: servers/nova-canvas-mcp-server.md
    - AWS Documentation: servers/aws-documentation-mcp-server.md
    - AWS Lambda: servers/lambda-mcp-server.md
    - AWS Diagram: servers/aws-diagram-mcp-server.md
    - AWS Terraform: servers/terraform-mcp-server.md
    - Git Repo Research: servers/git-repo-research-mcp-server.md
    - CloudFormation: servers/cfn-mcp-server.md
    - Finch: servers/finch-mcp-server.md
  - Samples:
    - Home: samples/index.md
    - MCP Integration with Amazon Bedrock Knowledge Bases: samples/mcp-integration-with-kb.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
