# Kubernetes Deployment template for ECR images
apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME
  namespace: NAMESPACE
  labels:
    app.kubernetes.io/name: APP_NAME
spec:
  replicas: REPLICAS
  selector:
    matchLabels:
      app.kubernetes.io/name: APP_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: APP_NAME
    spec:
      containers:
      - name: APP_NAME
        image: IMAGE_URI
        imagePullPolicy: Always
        ports:
        - containerPort: PORT
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        resources:
          requests:
            cpu: CPU
            memory: MEMORY
          limits:
            cpu: CPU
            memory: MEMORY
