# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Auto-generated operations metadata from botocore service model.

DO NOT EDIT — this file is auto-generated from the botocore service model.
"""

from awslabs.amazon_medialive_mcp_server.models import (
    AcceptInputDeviceTransferRequest,
    AcceptInputDeviceTransferResponse,
    BatchDeleteRequest,
    BatchDeleteResponse,
    BatchStartRequest,
    BatchStartResponse,
    BatchStopRequest,
    BatchStopResponse,
    BatchUpdateScheduleRequest,
    BatchUpdateScheduleResponse,
    CancelInputDeviceTransferRequest,
    CancelInputDeviceTransferResponse,
    ClaimDeviceRequest,
    ClaimDeviceResponse,
    CreateChannelPlacementGroupRequest,
    CreateChannelPlacementGroupResponse,
    CreateChannelRequest,
    CreateChannelResponse,
    CreateCloudWatchAlarmTemplateGroupRequest,
    CreateCloudWatchAlarmTemplateGroupResponse,
    CreateCloudWatchAlarmTemplateRequest,
    CreateCloudWatchAlarmTemplateResponse,
    CreateClusterRequest,
    CreateClusterResponse,
    CreateEventBridgeRuleTemplateGroupRequest,
    CreateEventBridgeRuleTemplateGroupResponse,
    CreateEventBridgeRuleTemplateRequest,
    CreateEventBridgeRuleTemplateResponse,
    CreateInputRequest,
    CreateInputResponse,
    CreateInputSecurityGroupRequest,
    CreateInputSecurityGroupResponse,
    CreateMultiplexProgramRequest,
    CreateMultiplexProgramResponse,
    CreateMultiplexRequest,
    CreateMultiplexResponse,
    CreateNetworkRequest,
    CreateNetworkResponse,
    CreateNodeRegistrationScriptRequest,
    CreateNodeRegistrationScriptResponse,
    CreateNodeRequest,
    CreateNodeResponse,
    CreatePartnerInputRequest,
    CreatePartnerInputResponse,
    CreateSdiSourceRequest,
    CreateSdiSourceResponse,
    CreateSignalMapRequest,
    CreateSignalMapResponse,
    CreateTagsRequest,
    DeleteChannelPlacementGroupRequest,
    DeleteChannelPlacementGroupResponse,
    DeleteChannelRequest,
    DeleteChannelResponse,
    DeleteCloudWatchAlarmTemplateGroupRequest,
    DeleteCloudWatchAlarmTemplateRequest,
    DeleteClusterRequest,
    DeleteClusterResponse,
    DeleteEventBridgeRuleTemplateGroupRequest,
    DeleteEventBridgeRuleTemplateRequest,
    DeleteInputRequest,
    DeleteInputResponse,
    DeleteInputSecurityGroupRequest,
    DeleteInputSecurityGroupResponse,
    DeleteMultiplexProgramRequest,
    DeleteMultiplexProgramResponse,
    DeleteMultiplexRequest,
    DeleteMultiplexResponse,
    DeleteNetworkRequest,
    DeleteNetworkResponse,
    DeleteNodeRequest,
    DeleteNodeResponse,
    DeleteReservationRequest,
    DeleteReservationResponse,
    DeleteScheduleRequest,
    DeleteScheduleResponse,
    DeleteSdiSourceRequest,
    DeleteSdiSourceResponse,
    DeleteSignalMapRequest,
    DeleteTagsRequest,
    DescribeAccountConfigurationRequest,
    DescribeAccountConfigurationResponse,
    DescribeChannelPlacementGroupRequest,
    DescribeChannelPlacementGroupResponse,
    DescribeChannelRequest,
    DescribeChannelResponse,
    DescribeClusterRequest,
    DescribeClusterResponse,
    DescribeInputDeviceRequest,
    DescribeInputDeviceResponse,
    DescribeInputDeviceThumbnailRequest,
    DescribeInputDeviceThumbnailResponse,
    DescribeInputRequest,
    DescribeInputResponse,
    DescribeInputSecurityGroupRequest,
    DescribeInputSecurityGroupResponse,
    DescribeMultiplexProgramRequest,
    DescribeMultiplexProgramResponse,
    DescribeMultiplexRequest,
    DescribeMultiplexResponse,
    DescribeNetworkRequest,
    DescribeNetworkResponse,
    DescribeNodeRequest,
    DescribeNodeResponse,
    DescribeOfferingRequest,
    DescribeOfferingResponse,
    DescribeReservationRequest,
    DescribeReservationResponse,
    DescribeScheduleRequest,
    DescribeScheduleResponse,
    DescribeSdiSourceRequest,
    DescribeSdiSourceResponse,
    DescribeThumbnailsRequest,
    DescribeThumbnailsResponse,
    GetCloudWatchAlarmTemplateGroupRequest,
    GetCloudWatchAlarmTemplateGroupResponse,
    GetCloudWatchAlarmTemplateRequest,
    GetCloudWatchAlarmTemplateResponse,
    GetEventBridgeRuleTemplateGroupRequest,
    GetEventBridgeRuleTemplateGroupResponse,
    GetEventBridgeRuleTemplateRequest,
    GetEventBridgeRuleTemplateResponse,
    GetSignalMapRequest,
    GetSignalMapResponse,
    ListChannelPlacementGroupsRequest,
    ListChannelPlacementGroupsResponse,
    ListChannelsRequest,
    ListChannelsResponse,
    ListCloudWatchAlarmTemplateGroupsRequest,
    ListCloudWatchAlarmTemplateGroupsResponse,
    ListCloudWatchAlarmTemplatesRequest,
    ListCloudWatchAlarmTemplatesResponse,
    ListClustersRequest,
    ListClustersResponse,
    ListEventBridgeRuleTemplateGroupsRequest,
    ListEventBridgeRuleTemplateGroupsResponse,
    ListEventBridgeRuleTemplatesRequest,
    ListEventBridgeRuleTemplatesResponse,
    ListInputDevicesRequest,
    ListInputDevicesResponse,
    ListInputDeviceTransfersRequest,
    ListInputDeviceTransfersResponse,
    ListInputSecurityGroupsRequest,
    ListInputSecurityGroupsResponse,
    ListInputsRequest,
    ListInputsResponse,
    ListMultiplexesRequest,
    ListMultiplexesResponse,
    ListMultiplexProgramsRequest,
    ListMultiplexProgramsResponse,
    ListNetworksRequest,
    ListNetworksResponse,
    ListNodesRequest,
    ListNodesResponse,
    ListOfferingsRequest,
    ListOfferingsResponse,
    ListReservationsRequest,
    ListReservationsResponse,
    ListSdiSourcesRequest,
    ListSdiSourcesResponse,
    ListSignalMapsRequest,
    ListSignalMapsResponse,
    ListTagsForResourceRequest,
    ListTagsForResourceResponse,
    ListVersionsRequest,
    ListVersionsResponse,
    PurchaseOfferingRequest,
    PurchaseOfferingResponse,
    RebootInputDeviceRequest,
    RebootInputDeviceResponse,
    RejectInputDeviceTransferRequest,
    RejectInputDeviceTransferResponse,
    RestartChannelPipelinesRequest,
    RestartChannelPipelinesResponse,
    StartChannelRequest,
    StartChannelResponse,
    StartDeleteMonitorDeploymentRequest,
    StartDeleteMonitorDeploymentResponse,
    StartInputDeviceMaintenanceWindowRequest,
    StartInputDeviceMaintenanceWindowResponse,
    StartInputDeviceRequest,
    StartInputDeviceResponse,
    StartMonitorDeploymentRequest,
    StartMonitorDeploymentResponse,
    StartMultiplexRequest,
    StartMultiplexResponse,
    StartUpdateSignalMapRequest,
    StartUpdateSignalMapResponse,
    StopChannelRequest,
    StopChannelResponse,
    StopInputDeviceRequest,
    StopInputDeviceResponse,
    StopMultiplexRequest,
    StopMultiplexResponse,
    TransferInputDeviceRequest,
    TransferInputDeviceResponse,
    UpdateAccountConfigurationRequest,
    UpdateAccountConfigurationResponse,
    UpdateChannelClassRequest,
    UpdateChannelClassResponse,
    UpdateChannelPlacementGroupRequest,
    UpdateChannelPlacementGroupResponse,
    UpdateChannelRequest,
    UpdateChannelResponse,
    UpdateCloudWatchAlarmTemplateGroupRequest,
    UpdateCloudWatchAlarmTemplateGroupResponse,
    UpdateCloudWatchAlarmTemplateRequest,
    UpdateCloudWatchAlarmTemplateResponse,
    UpdateClusterRequest,
    UpdateClusterResponse,
    UpdateEventBridgeRuleTemplateGroupRequest,
    UpdateEventBridgeRuleTemplateGroupResponse,
    UpdateEventBridgeRuleTemplateRequest,
    UpdateEventBridgeRuleTemplateResponse,
    UpdateInputDeviceRequest,
    UpdateInputDeviceResponse,
    UpdateInputRequest,
    UpdateInputResponse,
    UpdateInputSecurityGroupRequest,
    UpdateInputSecurityGroupResponse,
    UpdateMultiplexProgramRequest,
    UpdateMultiplexProgramResponse,
    UpdateMultiplexRequest,
    UpdateMultiplexResponse,
    UpdateNetworkRequest,
    UpdateNetworkResponse,
    UpdateNodeRequest,
    UpdateNodeResponse,
    UpdateNodeStateRequest,
    UpdateNodeStateResponse,
    UpdateReservationRequest,
    UpdateReservationResponse,
    UpdateSdiSourceRequest,
    UpdateSdiSourceResponse,
)


OPERATIONS = {
    'AcceptInputDeviceTransfer': {
        'name': 'AcceptInputDeviceTransfer',
        'tool_name': 'accept_input_device_transfer',
        'input_model': AcceptInputDeviceTransferRequest,
        'output_model': AcceptInputDeviceTransferResponse,
        'http_method': 'POST',
        'request_uri': '/prod/inputDevices/{inputDeviceId}/accept',
        'auto_description': 'Accept an incoming input device transfer. The ownership of the device will transfer to your AWS account.',
        'pagination': None,
    },
    'BatchDelete': {
        'name': 'BatchDelete',
        'tool_name': 'batch_delete',
        'input_model': BatchDeleteRequest,
        'output_model': BatchDeleteResponse,
        'http_method': 'POST',
        'request_uri': '/prod/batch/delete',
        'auto_description': 'Starts delete of resources.',
        'pagination': None,
    },
    'BatchStart': {
        'name': 'BatchStart',
        'tool_name': 'batch_start',
        'input_model': BatchStartRequest,
        'output_model': BatchStartResponse,
        'http_method': 'POST',
        'request_uri': '/prod/batch/start',
        'auto_description': 'Starts existing resources',
        'pagination': None,
    },
    'BatchStop': {
        'name': 'BatchStop',
        'tool_name': 'batch_stop',
        'input_model': BatchStopRequest,
        'output_model': BatchStopResponse,
        'http_method': 'POST',
        'request_uri': '/prod/batch/stop',
        'auto_description': 'Stops running resources',
        'pagination': None,
    },
    'BatchUpdateSchedule': {
        'name': 'BatchUpdateSchedule',
        'tool_name': 'batch_update_schedule',
        'input_model': BatchUpdateScheduleRequest,
        'output_model': BatchUpdateScheduleResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/channels/{channelId}/schedule',
        'auto_description': 'Update a channel schedule',
        'pagination': None,
    },
    'CancelInputDeviceTransfer': {
        'name': 'CancelInputDeviceTransfer',
        'tool_name': 'cancel_input_device_transfer',
        'input_model': CancelInputDeviceTransferRequest,
        'output_model': CancelInputDeviceTransferResponse,
        'http_method': 'POST',
        'request_uri': '/prod/inputDevices/{inputDeviceId}/cancel',
        'auto_description': 'Cancel an input device transfer that you have requested.',
        'pagination': None,
    },
    'ClaimDevice': {
        'name': 'ClaimDevice',
        'tool_name': 'claim_device',
        'input_model': ClaimDeviceRequest,
        'output_model': ClaimDeviceResponse,
        'http_method': 'POST',
        'request_uri': '/prod/claimDevice',
        'auto_description': 'Send a request to claim an AWS Elemental device that you have purchased from a third-party vendor. After the request succeeds, you will own the device.',
        'pagination': None,
    },
    'CreateChannel': {
        'name': 'CreateChannel',
        'tool_name': 'create_channel',
        'input_model': CreateChannelRequest,
        'output_model': CreateChannelResponse,
        'http_method': 'POST',
        'request_uri': '/prod/channels',
        'auto_description': 'Creates a new channel',
        'pagination': None,
    },
    'CreateInput': {
        'name': 'CreateInput',
        'tool_name': 'create_input',
        'input_model': CreateInputRequest,
        'output_model': CreateInputResponse,
        'http_method': 'POST',
        'request_uri': '/prod/inputs',
        'auto_description': 'Create an input',
        'pagination': None,
    },
    'CreateInputSecurityGroup': {
        'name': 'CreateInputSecurityGroup',
        'tool_name': 'create_input_security_group',
        'input_model': CreateInputSecurityGroupRequest,
        'output_model': CreateInputSecurityGroupResponse,
        'http_method': 'POST',
        'request_uri': '/prod/inputSecurityGroups',
        'auto_description': 'Creates a Input Security Group',
        'pagination': None,
    },
    'CreateMultiplex': {
        'name': 'CreateMultiplex',
        'tool_name': 'create_multiplex',
        'input_model': CreateMultiplexRequest,
        'output_model': CreateMultiplexResponse,
        'http_method': 'POST',
        'request_uri': '/prod/multiplexes',
        'auto_description': 'Create a new multiplex.',
        'pagination': None,
    },
    'CreateMultiplexProgram': {
        'name': 'CreateMultiplexProgram',
        'tool_name': 'create_multiplex_program',
        'input_model': CreateMultiplexProgramRequest,
        'output_model': CreateMultiplexProgramResponse,
        'http_method': 'POST',
        'request_uri': '/prod/multiplexes/{multiplexId}/programs',
        'auto_description': 'Create a new program in the multiplex.',
        'pagination': None,
    },
    'CreatePartnerInput': {
        'name': 'CreatePartnerInput',
        'tool_name': 'create_partner_input',
        'input_model': CreatePartnerInputRequest,
        'output_model': CreatePartnerInputResponse,
        'http_method': 'POST',
        'request_uri': '/prod/inputs/{inputId}/partners',
        'auto_description': 'Create a partner input',
        'pagination': None,
    },
    'CreateTags': {
        'name': 'CreateTags',
        'tool_name': 'create_tags',
        'input_model': CreateTagsRequest,
        'output_model': dict,
        'http_method': 'POST',
        'request_uri': '/prod/tags/{resource-arn}',
        'auto_description': 'Create tags for a resource',
        'pagination': None,
    },
    'DeleteChannel': {
        'name': 'DeleteChannel',
        'tool_name': 'delete_channel',
        'input_model': DeleteChannelRequest,
        'output_model': DeleteChannelResponse,
        'http_method': 'DELETE',
        'request_uri': '/prod/channels/{channelId}',
        'auto_description': 'Starts deletion of channel. The associated outputs are also deleted.',
        'pagination': None,
    },
    'DeleteInput': {
        'name': 'DeleteInput',
        'tool_name': 'delete_input',
        'input_model': DeleteInputRequest,
        'output_model': DeleteInputResponse,
        'http_method': 'DELETE',
        'request_uri': '/prod/inputs/{inputId}',
        'auto_description': 'Deletes the input end point',
        'pagination': None,
    },
    'DeleteInputSecurityGroup': {
        'name': 'DeleteInputSecurityGroup',
        'tool_name': 'delete_input_security_group',
        'input_model': DeleteInputSecurityGroupRequest,
        'output_model': DeleteInputSecurityGroupResponse,
        'http_method': 'DELETE',
        'request_uri': '/prod/inputSecurityGroups/{inputSecurityGroupId}',
        'auto_description': 'Deletes an Input Security Group',
        'pagination': None,
    },
    'DeleteMultiplex': {
        'name': 'DeleteMultiplex',
        'tool_name': 'delete_multiplex',
        'input_model': DeleteMultiplexRequest,
        'output_model': DeleteMultiplexResponse,
        'http_method': 'DELETE',
        'request_uri': '/prod/multiplexes/{multiplexId}',
        'auto_description': 'Delete a multiplex. The multiplex must be idle.',
        'pagination': None,
    },
    'DeleteMultiplexProgram': {
        'name': 'DeleteMultiplexProgram',
        'tool_name': 'delete_multiplex_program',
        'input_model': DeleteMultiplexProgramRequest,
        'output_model': DeleteMultiplexProgramResponse,
        'http_method': 'DELETE',
        'request_uri': '/prod/multiplexes/{multiplexId}/programs/{programName}',
        'auto_description': 'Delete a program from a multiplex.',
        'pagination': None,
    },
    'DeleteReservation': {
        'name': 'DeleteReservation',
        'tool_name': 'delete_reservation',
        'input_model': DeleteReservationRequest,
        'output_model': DeleteReservationResponse,
        'http_method': 'DELETE',
        'request_uri': '/prod/reservations/{reservationId}',
        'auto_description': 'Delete an expired reservation.',
        'pagination': None,
    },
    'DeleteSchedule': {
        'name': 'DeleteSchedule',
        'tool_name': 'delete_schedule',
        'input_model': DeleteScheduleRequest,
        'output_model': DeleteScheduleResponse,
        'http_method': 'DELETE',
        'request_uri': '/prod/channels/{channelId}/schedule',
        'auto_description': 'Delete all schedule actions on a channel.',
        'pagination': None,
    },
    'DeleteTags': {
        'name': 'DeleteTags',
        'tool_name': 'delete_tags',
        'input_model': DeleteTagsRequest,
        'output_model': dict,
        'http_method': 'DELETE',
        'request_uri': '/prod/tags/{resource-arn}',
        'auto_description': 'Removes tags for a resource',
        'pagination': None,
    },
    'DescribeAccountConfiguration': {
        'name': 'DescribeAccountConfiguration',
        'tool_name': 'describe_account_configuration',
        'input_model': DescribeAccountConfigurationRequest,
        'output_model': DescribeAccountConfigurationResponse,
        'http_method': 'GET',
        'request_uri': '/prod/accountConfiguration',
        'auto_description': 'Describe account configuration',
        'pagination': None,
    },
    'DescribeChannel': {
        'name': 'DescribeChannel',
        'tool_name': 'describe_channel',
        'input_model': DescribeChannelRequest,
        'output_model': DescribeChannelResponse,
        'http_method': 'GET',
        'request_uri': '/prod/channels/{channelId}',
        'auto_description': 'Gets details about a channel',
        'pagination': None,
    },
    'DescribeInput': {
        'name': 'DescribeInput',
        'tool_name': 'describe_input',
        'input_model': DescribeInputRequest,
        'output_model': DescribeInputResponse,
        'http_method': 'GET',
        'request_uri': '/prod/inputs/{inputId}',
        'auto_description': 'Produces details about an input',
        'pagination': None,
    },
    'DescribeInputDevice': {
        'name': 'DescribeInputDevice',
        'tool_name': 'describe_input_device',
        'input_model': DescribeInputDeviceRequest,
        'output_model': DescribeInputDeviceResponse,
        'http_method': 'GET',
        'request_uri': '/prod/inputDevices/{inputDeviceId}',
        'auto_description': 'Gets the details for the input device',
        'pagination': None,
    },
    'DescribeInputDeviceThumbnail': {
        'name': 'DescribeInputDeviceThumbnail',
        'tool_name': 'describe_input_device_thumbnail',
        'input_model': DescribeInputDeviceThumbnailRequest,
        'output_model': DescribeInputDeviceThumbnailResponse,
        'http_method': 'GET',
        'request_uri': '/prod/inputDevices/{inputDeviceId}/thumbnailData',
        'auto_description': 'Get the latest thumbnail data for the input device.',
        'pagination': None,
    },
    'DescribeInputSecurityGroup': {
        'name': 'DescribeInputSecurityGroup',
        'tool_name': 'describe_input_security_group',
        'input_model': DescribeInputSecurityGroupRequest,
        'output_model': DescribeInputSecurityGroupResponse,
        'http_method': 'GET',
        'request_uri': '/prod/inputSecurityGroups/{inputSecurityGroupId}',
        'auto_description': 'Produces a summary of an Input Security Group',
        'pagination': None,
    },
    'DescribeMultiplex': {
        'name': 'DescribeMultiplex',
        'tool_name': 'describe_multiplex',
        'input_model': DescribeMultiplexRequest,
        'output_model': DescribeMultiplexResponse,
        'http_method': 'GET',
        'request_uri': '/prod/multiplexes/{multiplexId}',
        'auto_description': 'Gets details about a multiplex.',
        'pagination': None,
    },
    'DescribeMultiplexProgram': {
        'name': 'DescribeMultiplexProgram',
        'tool_name': 'describe_multiplex_program',
        'input_model': DescribeMultiplexProgramRequest,
        'output_model': DescribeMultiplexProgramResponse,
        'http_method': 'GET',
        'request_uri': '/prod/multiplexes/{multiplexId}/programs/{programName}',
        'auto_description': 'Get the details for a program in a multiplex.',
        'pagination': None,
    },
    'DescribeOffering': {
        'name': 'DescribeOffering',
        'tool_name': 'describe_offering',
        'input_model': DescribeOfferingRequest,
        'output_model': DescribeOfferingResponse,
        'http_method': 'GET',
        'request_uri': '/prod/offerings/{offeringId}',
        'auto_description': 'Get details for an offering.',
        'pagination': None,
    },
    'DescribeReservation': {
        'name': 'DescribeReservation',
        'tool_name': 'describe_reservation',
        'input_model': DescribeReservationRequest,
        'output_model': DescribeReservationResponse,
        'http_method': 'GET',
        'request_uri': '/prod/reservations/{reservationId}',
        'auto_description': 'Get details for a reservation.',
        'pagination': None,
    },
    'DescribeSchedule': {
        'name': 'DescribeSchedule',
        'tool_name': 'describe_schedule',
        'input_model': DescribeScheduleRequest,
        'output_model': DescribeScheduleResponse,
        'http_method': 'GET',
        'request_uri': '/prod/channels/{channelId}/schedule',
        'auto_description': 'Get a channel schedule',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['ScheduleActions'],
            'limit_key': 'MaxResults',
        },
    },
    'DescribeThumbnails': {
        'name': 'DescribeThumbnails',
        'tool_name': 'describe_thumbnails',
        'input_model': DescribeThumbnailsRequest,
        'output_model': DescribeThumbnailsResponse,
        'http_method': 'GET',
        'request_uri': '/prod/channels/{channelId}/thumbnails',
        'auto_description': 'Describe the latest thumbnails data.',
        'pagination': None,
    },
    'ListChannels': {
        'name': 'ListChannels',
        'tool_name': 'list_channels',
        'input_model': ListChannelsRequest,
        'output_model': ListChannelsResponse,
        'http_method': 'GET',
        'request_uri': '/prod/channels',
        'auto_description': 'Produces list of channels that have been created',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['Channels'],
            'limit_key': 'MaxResults',
        },
    },
    'ListInputDeviceTransfers': {
        'name': 'ListInputDeviceTransfers',
        'tool_name': 'list_input_device_transfers',
        'input_model': ListInputDeviceTransfersRequest,
        'output_model': ListInputDeviceTransfersResponse,
        'http_method': 'GET',
        'request_uri': '/prod/inputDeviceTransfers',
        'auto_description': 'List input devices that are currently being transferred. List input devices that you are transferring from your AWS account or input devices that another AWS account is transferring to you.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['InputDeviceTransfers'],
            'limit_key': 'MaxResults',
        },
    },
    'ListInputDevices': {
        'name': 'ListInputDevices',
        'tool_name': 'list_input_devices',
        'input_model': ListInputDevicesRequest,
        'output_model': ListInputDevicesResponse,
        'http_method': 'GET',
        'request_uri': '/prod/inputDevices',
        'auto_description': 'List input devices',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['InputDevices'],
            'limit_key': 'MaxResults',
        },
    },
    'ListInputSecurityGroups': {
        'name': 'ListInputSecurityGroups',
        'tool_name': 'list_input_security_groups',
        'input_model': ListInputSecurityGroupsRequest,
        'output_model': ListInputSecurityGroupsResponse,
        'http_method': 'GET',
        'request_uri': '/prod/inputSecurityGroups',
        'auto_description': 'Produces a list of Input Security Groups for an account',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['InputSecurityGroups'],
            'limit_key': 'MaxResults',
        },
    },
    'ListInputs': {
        'name': 'ListInputs',
        'tool_name': 'list_inputs',
        'input_model': ListInputsRequest,
        'output_model': ListInputsResponse,
        'http_method': 'GET',
        'request_uri': '/prod/inputs',
        'auto_description': 'Produces list of inputs that have been created',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['Inputs'],
            'limit_key': 'MaxResults',
        },
    },
    'ListMultiplexPrograms': {
        'name': 'ListMultiplexPrograms',
        'tool_name': 'list_multiplex_programs',
        'input_model': ListMultiplexProgramsRequest,
        'output_model': ListMultiplexProgramsResponse,
        'http_method': 'GET',
        'request_uri': '/prod/multiplexes/{multiplexId}/programs',
        'auto_description': 'List the programs that currently exist for a specific multiplex.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['MultiplexPrograms'],
            'limit_key': 'MaxResults',
        },
    },
    'ListMultiplexes': {
        'name': 'ListMultiplexes',
        'tool_name': 'list_multiplexes',
        'input_model': ListMultiplexesRequest,
        'output_model': ListMultiplexesResponse,
        'http_method': 'GET',
        'request_uri': '/prod/multiplexes',
        'auto_description': 'Retrieve a list of the existing multiplexes.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['Multiplexes'],
            'limit_key': 'MaxResults',
        },
    },
    'ListOfferings': {
        'name': 'ListOfferings',
        'tool_name': 'list_offerings',
        'input_model': ListOfferingsRequest,
        'output_model': ListOfferingsResponse,
        'http_method': 'GET',
        'request_uri': '/prod/offerings',
        'auto_description': 'List offerings available for purchase.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['Offerings'],
            'limit_key': 'MaxResults',
        },
    },
    'ListReservations': {
        'name': 'ListReservations',
        'tool_name': 'list_reservations',
        'input_model': ListReservationsRequest,
        'output_model': ListReservationsResponse,
        'http_method': 'GET',
        'request_uri': '/prod/reservations',
        'auto_description': 'List purchased reservations.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['Reservations'],
            'limit_key': 'MaxResults',
        },
    },
    'ListTagsForResource': {
        'name': 'ListTagsForResource',
        'tool_name': 'list_tags_for_resource',
        'input_model': ListTagsForResourceRequest,
        'output_model': ListTagsForResourceResponse,
        'http_method': 'GET',
        'request_uri': '/prod/tags/{resource-arn}',
        'auto_description': 'Produces list of tags that have been created for a resource',
        'pagination': None,
    },
    'PurchaseOffering': {
        'name': 'PurchaseOffering',
        'tool_name': 'purchase_offering',
        'input_model': PurchaseOfferingRequest,
        'output_model': PurchaseOfferingResponse,
        'http_method': 'POST',
        'request_uri': '/prod/offerings/{offeringId}/purchase',
        'auto_description': 'Purchase an offering and create a reservation.',
        'pagination': None,
    },
    'RebootInputDevice': {
        'name': 'RebootInputDevice',
        'tool_name': 'reboot_input_device',
        'input_model': RebootInputDeviceRequest,
        'output_model': RebootInputDeviceResponse,
        'http_method': 'POST',
        'request_uri': '/prod/inputDevices/{inputDeviceId}/reboot',
        'auto_description': 'Send a reboot command to the specified input device. The device will begin rebooting within a few seconds of sending the command. When the reboot is complete, the device\u2019s connection status will change to connected.',
        'pagination': None,
    },
    'RejectInputDeviceTransfer': {
        'name': 'RejectInputDeviceTransfer',
        'tool_name': 'reject_input_device_transfer',
        'input_model': RejectInputDeviceTransferRequest,
        'output_model': RejectInputDeviceTransferResponse,
        'http_method': 'POST',
        'request_uri': '/prod/inputDevices/{inputDeviceId}/reject',
        'auto_description': 'Reject the transfer of the specified input device to your AWS account.',
        'pagination': None,
    },
    'StartChannel': {
        'name': 'StartChannel',
        'tool_name': 'start_channel',
        'input_model': StartChannelRequest,
        'output_model': StartChannelResponse,
        'http_method': 'POST',
        'request_uri': '/prod/channels/{channelId}/start',
        'auto_description': 'Starts an existing channel',
        'pagination': None,
    },
    'StartInputDevice': {
        'name': 'StartInputDevice',
        'tool_name': 'start_input_device',
        'input_model': StartInputDeviceRequest,
        'output_model': StartInputDeviceResponse,
        'http_method': 'POST',
        'request_uri': '/prod/inputDevices/{inputDeviceId}/start',
        'auto_description': 'Start an input device that is attached to a MediaConnect flow. (There is no need to start a device that is attached to a MediaLive input; MediaLive starts the device when the channel starts.)',
        'pagination': None,
    },
    'StartInputDeviceMaintenanceWindow': {
        'name': 'StartInputDeviceMaintenanceWindow',
        'tool_name': 'start_input_device_maintenance_window',
        'input_model': StartInputDeviceMaintenanceWindowRequest,
        'output_model': StartInputDeviceMaintenanceWindowResponse,
        'http_method': 'POST',
        'request_uri': '/prod/inputDevices/{inputDeviceId}/startInputDeviceMaintenanceWindow',
        'auto_description': 'Start a maintenance window for the specified input device. Starting a maintenance window will give the device up to two hours to install software. If the device was streaming prior to the maintenance, it will resume streaming when the software is fully installed. Devices automatically install updates while they are powered on and their MediaLive channels are stopped. A maintenance window allows you to update a device without having to stop MediaLive channels that use the device. The device must remain powered on and connected to the internet for the duration of the maintenance.',
        'pagination': None,
    },
    'StartMultiplex': {
        'name': 'StartMultiplex',
        'tool_name': 'start_multiplex',
        'input_model': StartMultiplexRequest,
        'output_model': StartMultiplexResponse,
        'http_method': 'POST',
        'request_uri': '/prod/multiplexes/{multiplexId}/start',
        'auto_description': 'Start (run) the multiplex. Starting the multiplex does not start the channels. You must explicitly start each channel.',
        'pagination': None,
    },
    'StopChannel': {
        'name': 'StopChannel',
        'tool_name': 'stop_channel',
        'input_model': StopChannelRequest,
        'output_model': StopChannelResponse,
        'http_method': 'POST',
        'request_uri': '/prod/channels/{channelId}/stop',
        'auto_description': 'Stops a running channel',
        'pagination': None,
    },
    'StopInputDevice': {
        'name': 'StopInputDevice',
        'tool_name': 'stop_input_device',
        'input_model': StopInputDeviceRequest,
        'output_model': StopInputDeviceResponse,
        'http_method': 'POST',
        'request_uri': '/prod/inputDevices/{inputDeviceId}/stop',
        'auto_description': 'Stop an input device that is attached to a MediaConnect flow. (There is no need to stop a device that is attached to a MediaLive input; MediaLive automatically stops the device when the channel stops.)',
        'pagination': None,
    },
    'StopMultiplex': {
        'name': 'StopMultiplex',
        'tool_name': 'stop_multiplex',
        'input_model': StopMultiplexRequest,
        'output_model': StopMultiplexResponse,
        'http_method': 'POST',
        'request_uri': '/prod/multiplexes/{multiplexId}/stop',
        'auto_description': 'Stops a running multiplex. If the multiplex isn\u0027t running, this action has no effect.',
        'pagination': None,
    },
    'TransferInputDevice': {
        'name': 'TransferInputDevice',
        'tool_name': 'transfer_input_device',
        'input_model': TransferInputDeviceRequest,
        'output_model': TransferInputDeviceResponse,
        'http_method': 'POST',
        'request_uri': '/prod/inputDevices/{inputDeviceId}/transfer',
        'auto_description': 'Start an input device transfer to another AWS account. After you make the request, the other account must accept or reject the transfer.',
        'pagination': None,
    },
    'UpdateAccountConfiguration': {
        'name': 'UpdateAccountConfiguration',
        'tool_name': 'update_account_configuration',
        'input_model': UpdateAccountConfigurationRequest,
        'output_model': UpdateAccountConfigurationResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/accountConfiguration',
        'auto_description': 'Update account configuration',
        'pagination': None,
    },
    'UpdateChannel': {
        'name': 'UpdateChannel',
        'tool_name': 'update_channel',
        'input_model': UpdateChannelRequest,
        'output_model': UpdateChannelResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/channels/{channelId}',
        'auto_description': 'Updates a channel.',
        'pagination': None,
    },
    'UpdateChannelClass': {
        'name': 'UpdateChannelClass',
        'tool_name': 'update_channel_class',
        'input_model': UpdateChannelClassRequest,
        'output_model': UpdateChannelClassResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/channels/{channelId}/channelClass',
        'auto_description': 'Changes the class of the channel.',
        'pagination': None,
    },
    'UpdateInput': {
        'name': 'UpdateInput',
        'tool_name': 'update_input',
        'input_model': UpdateInputRequest,
        'output_model': UpdateInputResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/inputs/{inputId}',
        'auto_description': 'Updates an input.',
        'pagination': None,
    },
    'UpdateInputDevice': {
        'name': 'UpdateInputDevice',
        'tool_name': 'update_input_device',
        'input_model': UpdateInputDeviceRequest,
        'output_model': UpdateInputDeviceResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/inputDevices/{inputDeviceId}',
        'auto_description': 'Updates the parameters for the input device.',
        'pagination': None,
    },
    'UpdateInputSecurityGroup': {
        'name': 'UpdateInputSecurityGroup',
        'tool_name': 'update_input_security_group',
        'input_model': UpdateInputSecurityGroupRequest,
        'output_model': UpdateInputSecurityGroupResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/inputSecurityGroups/{inputSecurityGroupId}',
        'auto_description': 'Update an Input Security Group\u0027s Whilelists.',
        'pagination': None,
    },
    'UpdateMultiplex': {
        'name': 'UpdateMultiplex',
        'tool_name': 'update_multiplex',
        'input_model': UpdateMultiplexRequest,
        'output_model': UpdateMultiplexResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/multiplexes/{multiplexId}',
        'auto_description': 'Updates a multiplex.',
        'pagination': None,
    },
    'UpdateMultiplexProgram': {
        'name': 'UpdateMultiplexProgram',
        'tool_name': 'update_multiplex_program',
        'input_model': UpdateMultiplexProgramRequest,
        'output_model': UpdateMultiplexProgramResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/multiplexes/{multiplexId}/programs/{programName}',
        'auto_description': 'Update a program in a multiplex.',
        'pagination': None,
    },
    'UpdateReservation': {
        'name': 'UpdateReservation',
        'tool_name': 'update_reservation',
        'input_model': UpdateReservationRequest,
        'output_model': UpdateReservationResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/reservations/{reservationId}',
        'auto_description': 'Update reservation.',
        'pagination': None,
    },
    'RestartChannelPipelines': {
        'name': 'RestartChannelPipelines',
        'tool_name': 'restart_channel_pipelines',
        'input_model': RestartChannelPipelinesRequest,
        'output_model': RestartChannelPipelinesResponse,
        'http_method': 'POST',
        'request_uri': '/prod/channels/{channelId}/restartChannelPipelines',
        'auto_description': 'Restart pipelines in one channel that is currently running.',
        'pagination': None,
    },
    'CreateCloudWatchAlarmTemplate': {
        'name': 'CreateCloudWatchAlarmTemplate',
        'tool_name': 'create_cloud_watch_alarm_template',
        'input_model': CreateCloudWatchAlarmTemplateRequest,
        'output_model': CreateCloudWatchAlarmTemplateResponse,
        'http_method': 'POST',
        'request_uri': '/prod/cloudwatch-alarm-templates',
        'auto_description': 'Creates a cloudwatch alarm template to dynamically generate cloudwatch metric alarms on targeted resource types.',
        'pagination': None,
    },
    'CreateCloudWatchAlarmTemplateGroup': {
        'name': 'CreateCloudWatchAlarmTemplateGroup',
        'tool_name': 'create_cloud_watch_alarm_template_group',
        'input_model': CreateCloudWatchAlarmTemplateGroupRequest,
        'output_model': CreateCloudWatchAlarmTemplateGroupResponse,
        'http_method': 'POST',
        'request_uri': '/prod/cloudwatch-alarm-template-groups',
        'auto_description': 'Creates a cloudwatch alarm template group to group your cloudwatch alarm templates and to attach to signal maps for dynamically creating alarms.',
        'pagination': None,
    },
    'CreateEventBridgeRuleTemplate': {
        'name': 'CreateEventBridgeRuleTemplate',
        'tool_name': 'create_event_bridge_rule_template',
        'input_model': CreateEventBridgeRuleTemplateRequest,
        'output_model': CreateEventBridgeRuleTemplateResponse,
        'http_method': 'POST',
        'request_uri': '/prod/eventbridge-rule-templates',
        'auto_description': 'Creates an eventbridge rule template to monitor events and send notifications to your targeted resources.',
        'pagination': None,
    },
    'CreateEventBridgeRuleTemplateGroup': {
        'name': 'CreateEventBridgeRuleTemplateGroup',
        'tool_name': 'create_event_bridge_rule_template_group',
        'input_model': CreateEventBridgeRuleTemplateGroupRequest,
        'output_model': CreateEventBridgeRuleTemplateGroupResponse,
        'http_method': 'POST',
        'request_uri': '/prod/eventbridge-rule-template-groups',
        'auto_description': 'Creates an eventbridge rule template group to group your eventbridge rule templates and to attach to signal maps for dynamically creating notification rules.',
        'pagination': None,
    },
    'CreateSignalMap': {
        'name': 'CreateSignalMap',
        'tool_name': 'create_signal_map',
        'input_model': CreateSignalMapRequest,
        'output_model': CreateSignalMapResponse,
        'http_method': 'POST',
        'request_uri': '/prod/signal-maps',
        'auto_description': 'Initiates the creation of a new signal map. Will discover a new mediaResourceMap based on the provided discoveryEntryPointArn.',
        'pagination': None,
    },
    'DeleteCloudWatchAlarmTemplate': {
        'name': 'DeleteCloudWatchAlarmTemplate',
        'tool_name': 'delete_cloud_watch_alarm_template',
        'input_model': DeleteCloudWatchAlarmTemplateRequest,
        'output_model': dict,
        'http_method': 'DELETE',
        'request_uri': '/prod/cloudwatch-alarm-templates/{identifier}',
        'auto_description': 'Deletes a cloudwatch alarm template.',
        'pagination': None,
    },
    'DeleteCloudWatchAlarmTemplateGroup': {
        'name': 'DeleteCloudWatchAlarmTemplateGroup',
        'tool_name': 'delete_cloud_watch_alarm_template_group',
        'input_model': DeleteCloudWatchAlarmTemplateGroupRequest,
        'output_model': dict,
        'http_method': 'DELETE',
        'request_uri': '/prod/cloudwatch-alarm-template-groups/{identifier}',
        'auto_description': 'Deletes a cloudwatch alarm template group. You must detach this group from all signal maps and ensure its existing templates are moved to another group or deleted.',
        'pagination': None,
    },
    'DeleteEventBridgeRuleTemplate': {
        'name': 'DeleteEventBridgeRuleTemplate',
        'tool_name': 'delete_event_bridge_rule_template',
        'input_model': DeleteEventBridgeRuleTemplateRequest,
        'output_model': dict,
        'http_method': 'DELETE',
        'request_uri': '/prod/eventbridge-rule-templates/{identifier}',
        'auto_description': 'Deletes an eventbridge rule template.',
        'pagination': None,
    },
    'DeleteEventBridgeRuleTemplateGroup': {
        'name': 'DeleteEventBridgeRuleTemplateGroup',
        'tool_name': 'delete_event_bridge_rule_template_group',
        'input_model': DeleteEventBridgeRuleTemplateGroupRequest,
        'output_model': dict,
        'http_method': 'DELETE',
        'request_uri': '/prod/eventbridge-rule-template-groups/{identifier}',
        'auto_description': 'Deletes an eventbridge rule template group. You must detach this group from all signal maps and ensure its existing templates are moved to another group or deleted.',
        'pagination': None,
    },
    'DeleteSignalMap': {
        'name': 'DeleteSignalMap',
        'tool_name': 'delete_signal_map',
        'input_model': DeleteSignalMapRequest,
        'output_model': dict,
        'http_method': 'DELETE',
        'request_uri': '/prod/signal-maps/{identifier}',
        'auto_description': 'Deletes the specified signal map.',
        'pagination': None,
    },
    'GetCloudWatchAlarmTemplate': {
        'name': 'GetCloudWatchAlarmTemplate',
        'tool_name': 'get_cloud_watch_alarm_template',
        'input_model': GetCloudWatchAlarmTemplateRequest,
        'output_model': GetCloudWatchAlarmTemplateResponse,
        'http_method': 'GET',
        'request_uri': '/prod/cloudwatch-alarm-templates/{identifier}',
        'auto_description': 'Retrieves the specified cloudwatch alarm template.',
        'pagination': None,
    },
    'GetCloudWatchAlarmTemplateGroup': {
        'name': 'GetCloudWatchAlarmTemplateGroup',
        'tool_name': 'get_cloud_watch_alarm_template_group',
        'input_model': GetCloudWatchAlarmTemplateGroupRequest,
        'output_model': GetCloudWatchAlarmTemplateGroupResponse,
        'http_method': 'GET',
        'request_uri': '/prod/cloudwatch-alarm-template-groups/{identifier}',
        'auto_description': 'Retrieves the specified cloudwatch alarm template group.',
        'pagination': None,
    },
    'GetEventBridgeRuleTemplate': {
        'name': 'GetEventBridgeRuleTemplate',
        'tool_name': 'get_event_bridge_rule_template',
        'input_model': GetEventBridgeRuleTemplateRequest,
        'output_model': GetEventBridgeRuleTemplateResponse,
        'http_method': 'GET',
        'request_uri': '/prod/eventbridge-rule-templates/{identifier}',
        'auto_description': 'Retrieves the specified eventbridge rule template.',
        'pagination': None,
    },
    'GetEventBridgeRuleTemplateGroup': {
        'name': 'GetEventBridgeRuleTemplateGroup',
        'tool_name': 'get_event_bridge_rule_template_group',
        'input_model': GetEventBridgeRuleTemplateGroupRequest,
        'output_model': GetEventBridgeRuleTemplateGroupResponse,
        'http_method': 'GET',
        'request_uri': '/prod/eventbridge-rule-template-groups/{identifier}',
        'auto_description': 'Retrieves the specified eventbridge rule template group.',
        'pagination': None,
    },
    'GetSignalMap': {
        'name': 'GetSignalMap',
        'tool_name': 'get_signal_map',
        'input_model': GetSignalMapRequest,
        'output_model': GetSignalMapResponse,
        'http_method': 'GET',
        'request_uri': '/prod/signal-maps/{identifier}',
        'auto_description': 'Retrieves the specified signal map.',
        'pagination': None,
    },
    'ListCloudWatchAlarmTemplateGroups': {
        'name': 'ListCloudWatchAlarmTemplateGroups',
        'tool_name': 'list_cloud_watch_alarm_template_groups',
        'input_model': ListCloudWatchAlarmTemplateGroupsRequest,
        'output_model': ListCloudWatchAlarmTemplateGroupsResponse,
        'http_method': 'GET',
        'request_uri': '/prod/cloudwatch-alarm-template-groups',
        'auto_description': 'Lists cloudwatch alarm template groups.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['CloudWatchAlarmTemplateGroups'],
            'limit_key': 'MaxResults',
        },
    },
    'ListCloudWatchAlarmTemplates': {
        'name': 'ListCloudWatchAlarmTemplates',
        'tool_name': 'list_cloud_watch_alarm_templates',
        'input_model': ListCloudWatchAlarmTemplatesRequest,
        'output_model': ListCloudWatchAlarmTemplatesResponse,
        'http_method': 'GET',
        'request_uri': '/prod/cloudwatch-alarm-templates',
        'auto_description': 'Lists cloudwatch alarm templates.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['CloudWatchAlarmTemplates'],
            'limit_key': 'MaxResults',
        },
    },
    'ListEventBridgeRuleTemplateGroups': {
        'name': 'ListEventBridgeRuleTemplateGroups',
        'tool_name': 'list_event_bridge_rule_template_groups',
        'input_model': ListEventBridgeRuleTemplateGroupsRequest,
        'output_model': ListEventBridgeRuleTemplateGroupsResponse,
        'http_method': 'GET',
        'request_uri': '/prod/eventbridge-rule-template-groups',
        'auto_description': 'Lists eventbridge rule template groups.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['EventBridgeRuleTemplateGroups'],
            'limit_key': 'MaxResults',
        },
    },
    'ListEventBridgeRuleTemplates': {
        'name': 'ListEventBridgeRuleTemplates',
        'tool_name': 'list_event_bridge_rule_templates',
        'input_model': ListEventBridgeRuleTemplatesRequest,
        'output_model': ListEventBridgeRuleTemplatesResponse,
        'http_method': 'GET',
        'request_uri': '/prod/eventbridge-rule-templates',
        'auto_description': 'Lists eventbridge rule templates.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['EventBridgeRuleTemplates'],
            'limit_key': 'MaxResults',
        },
    },
    'ListSignalMaps': {
        'name': 'ListSignalMaps',
        'tool_name': 'list_signal_maps',
        'input_model': ListSignalMapsRequest,
        'output_model': ListSignalMapsResponse,
        'http_method': 'GET',
        'request_uri': '/prod/signal-maps',
        'auto_description': 'Lists signal maps.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['SignalMaps'],
            'limit_key': 'MaxResults',
        },
    },
    'StartDeleteMonitorDeployment': {
        'name': 'StartDeleteMonitorDeployment',
        'tool_name': 'start_delete_monitor_deployment',
        'input_model': StartDeleteMonitorDeploymentRequest,
        'output_model': StartDeleteMonitorDeploymentResponse,
        'http_method': 'DELETE',
        'request_uri': '/prod/signal-maps/{identifier}/monitor-deployment',
        'auto_description': 'Initiates a deployment to delete the monitor of the specified signal map.',
        'pagination': None,
    },
    'StartMonitorDeployment': {
        'name': 'StartMonitorDeployment',
        'tool_name': 'start_monitor_deployment',
        'input_model': StartMonitorDeploymentRequest,
        'output_model': StartMonitorDeploymentResponse,
        'http_method': 'POST',
        'request_uri': '/prod/signal-maps/{identifier}/monitor-deployment',
        'auto_description': 'Initiates a deployment to deploy the latest monitor of the specified signal map.',
        'pagination': None,
    },
    'StartUpdateSignalMap': {
        'name': 'StartUpdateSignalMap',
        'tool_name': 'start_update_signal_map',
        'input_model': StartUpdateSignalMapRequest,
        'output_model': StartUpdateSignalMapResponse,
        'http_method': 'PATCH',
        'request_uri': '/prod/signal-maps/{identifier}',
        'auto_description': 'Initiates an update for the specified signal map. Will discover a new signal map if a changed discoveryEntryPointArn is provided.',
        'pagination': None,
    },
    'UpdateCloudWatchAlarmTemplate': {
        'name': 'UpdateCloudWatchAlarmTemplate',
        'tool_name': 'update_cloud_watch_alarm_template',
        'input_model': UpdateCloudWatchAlarmTemplateRequest,
        'output_model': UpdateCloudWatchAlarmTemplateResponse,
        'http_method': 'PATCH',
        'request_uri': '/prod/cloudwatch-alarm-templates/{identifier}',
        'auto_description': 'Updates the specified cloudwatch alarm template.',
        'pagination': None,
    },
    'UpdateCloudWatchAlarmTemplateGroup': {
        'name': 'UpdateCloudWatchAlarmTemplateGroup',
        'tool_name': 'update_cloud_watch_alarm_template_group',
        'input_model': UpdateCloudWatchAlarmTemplateGroupRequest,
        'output_model': UpdateCloudWatchAlarmTemplateGroupResponse,
        'http_method': 'PATCH',
        'request_uri': '/prod/cloudwatch-alarm-template-groups/{identifier}',
        'auto_description': 'Updates the specified cloudwatch alarm template group.',
        'pagination': None,
    },
    'UpdateEventBridgeRuleTemplate': {
        'name': 'UpdateEventBridgeRuleTemplate',
        'tool_name': 'update_event_bridge_rule_template',
        'input_model': UpdateEventBridgeRuleTemplateRequest,
        'output_model': UpdateEventBridgeRuleTemplateResponse,
        'http_method': 'PATCH',
        'request_uri': '/prod/eventbridge-rule-templates/{identifier}',
        'auto_description': 'Updates the specified eventbridge rule template.',
        'pagination': None,
    },
    'UpdateEventBridgeRuleTemplateGroup': {
        'name': 'UpdateEventBridgeRuleTemplateGroup',
        'tool_name': 'update_event_bridge_rule_template_group',
        'input_model': UpdateEventBridgeRuleTemplateGroupRequest,
        'output_model': UpdateEventBridgeRuleTemplateGroupResponse,
        'http_method': 'PATCH',
        'request_uri': '/prod/eventbridge-rule-template-groups/{identifier}',
        'auto_description': 'Updates the specified eventbridge rule template group.',
        'pagination': None,
    },
    'CreateChannelPlacementGroup': {
        'name': 'CreateChannelPlacementGroup',
        'tool_name': 'create_channel_placement_group',
        'input_model': CreateChannelPlacementGroupRequest,
        'output_model': CreateChannelPlacementGroupResponse,
        'http_method': 'POST',
        'request_uri': '/prod/clusters/{clusterId}/channelplacementgroups',
        'auto_description': 'Create a ChannelPlacementGroup in the specified Cluster. As part of the create operation, you specify the Nodes to attach the group to.After you create a ChannelPlacementGroup, you add Channels to the group (you do this by modifying the Channels to add them to a specific group). You now have an association of Channels to ChannelPlacementGroup, and ChannelPlacementGroup to Nodes. This association means that all the Channels in the group are able to run on any of the Nodes associated with the group.',
        'pagination': None,
    },
    'CreateCluster': {
        'name': 'CreateCluster',
        'tool_name': 'create_cluster',
        'input_model': CreateClusterRequest,
        'output_model': CreateClusterResponse,
        'http_method': 'POST',
        'request_uri': '/prod/clusters',
        'auto_description': 'Create a new Cluster.',
        'pagination': None,
    },
    'CreateNetwork': {
        'name': 'CreateNetwork',
        'tool_name': 'create_network',
        'input_model': CreateNetworkRequest,
        'output_model': CreateNetworkResponse,
        'http_method': 'POST',
        'request_uri': '/prod/networks',
        'auto_description': 'Create as many Networks as you need. You will associate one or more Clusters with each Network.Each Network provides MediaLive Anywhere with required information about the network in your organization that you are using for video encoding using MediaLive.',
        'pagination': None,
    },
    'CreateNode': {
        'name': 'CreateNode',
        'tool_name': 'create_node',
        'input_model': CreateNodeRequest,
        'output_model': CreateNodeResponse,
        'http_method': 'POST',
        'request_uri': '/prod/clusters/{clusterId}/nodes',
        'auto_description': 'Create a Node in the specified Cluster. You can also create Nodes using the CreateNodeRegistrationScript. Note that you can\u0027t move a Node to another Cluster.',
        'pagination': None,
    },
    'CreateNodeRegistrationScript': {
        'name': 'CreateNodeRegistrationScript',
        'tool_name': 'create_node_registration_script',
        'input_model': CreateNodeRegistrationScriptRequest,
        'output_model': CreateNodeRegistrationScriptResponse,
        'http_method': 'POST',
        'request_uri': '/prod/clusters/{clusterId}/nodeRegistrationScript',
        'auto_description': 'Create the Register Node script for all the nodes intended for a specific Cluster. You will then run the script on each hardware unit that is intended for that Cluster. The script creates a Node in the specified Cluster. It then binds the Node to this hardware unit, and activates the node hardware for use with MediaLive Anywhere.',
        'pagination': None,
    },
    'DeleteChannelPlacementGroup': {
        'name': 'DeleteChannelPlacementGroup',
        'tool_name': 'delete_channel_placement_group',
        'input_model': DeleteChannelPlacementGroupRequest,
        'output_model': DeleteChannelPlacementGroupResponse,
        'http_method': 'DELETE',
        'request_uri': '/prod/clusters/{clusterId}/channelplacementgroups/{channelPlacementGroupId}',
        'auto_description': 'Delete the specified ChannelPlacementGroup that exists in the specified Cluster.',
        'pagination': None,
    },
    'DeleteCluster': {
        'name': 'DeleteCluster',
        'tool_name': 'delete_cluster',
        'input_model': DeleteClusterRequest,
        'output_model': DeleteClusterResponse,
        'http_method': 'DELETE',
        'request_uri': '/prod/clusters/{clusterId}',
        'auto_description': 'Delete a Cluster. The Cluster must be idle.',
        'pagination': None,
    },
    'DeleteNetwork': {
        'name': 'DeleteNetwork',
        'tool_name': 'delete_network',
        'input_model': DeleteNetworkRequest,
        'output_model': DeleteNetworkResponse,
        'http_method': 'DELETE',
        'request_uri': '/prod/networks/{networkId}',
        'auto_description': 'Delete a Network. The Network must have no resources associated with it.',
        'pagination': None,
    },
    'DeleteNode': {
        'name': 'DeleteNode',
        'tool_name': 'delete_node',
        'input_model': DeleteNodeRequest,
        'output_model': DeleteNodeResponse,
        'http_method': 'DELETE',
        'request_uri': '/prod/clusters/{clusterId}/nodes/{nodeId}',
        'auto_description': 'Delete a Node. The Node must be IDLE.',
        'pagination': None,
    },
    'DescribeChannelPlacementGroup': {
        'name': 'DescribeChannelPlacementGroup',
        'tool_name': 'describe_channel_placement_group',
        'input_model': DescribeChannelPlacementGroupRequest,
        'output_model': DescribeChannelPlacementGroupResponse,
        'http_method': 'GET',
        'request_uri': '/prod/clusters/{clusterId}/channelplacementgroups/{channelPlacementGroupId}',
        'auto_description': 'Get details about a ChannelPlacementGroup.',
        'pagination': None,
    },
    'DescribeCluster': {
        'name': 'DescribeCluster',
        'tool_name': 'describe_cluster',
        'input_model': DescribeClusterRequest,
        'output_model': DescribeClusterResponse,
        'http_method': 'GET',
        'request_uri': '/prod/clusters/{clusterId}',
        'auto_description': 'Get details about a Cluster.',
        'pagination': None,
    },
    'DescribeNetwork': {
        'name': 'DescribeNetwork',
        'tool_name': 'describe_network',
        'input_model': DescribeNetworkRequest,
        'output_model': DescribeNetworkResponse,
        'http_method': 'GET',
        'request_uri': '/prod/networks/{networkId}',
        'auto_description': 'Get details about a Network.',
        'pagination': None,
    },
    'DescribeNode': {
        'name': 'DescribeNode',
        'tool_name': 'describe_node',
        'input_model': DescribeNodeRequest,
        'output_model': DescribeNodeResponse,
        'http_method': 'GET',
        'request_uri': '/prod/clusters/{clusterId}/nodes/{nodeId}',
        'auto_description': 'Get details about a Node in the specified Cluster.',
        'pagination': None,
    },
    'ListChannelPlacementGroups': {
        'name': 'ListChannelPlacementGroups',
        'tool_name': 'list_channel_placement_groups',
        'input_model': ListChannelPlacementGroupsRequest,
        'output_model': ListChannelPlacementGroupsResponse,
        'http_method': 'GET',
        'request_uri': '/prod/clusters/{clusterId}/channelplacementgroups',
        'auto_description': 'Retrieve the list of ChannelPlacementGroups in the specified Cluster.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['ChannelPlacementGroups'],
            'limit_key': 'MaxResults',
        },
    },
    'ListClusters': {
        'name': 'ListClusters',
        'tool_name': 'list_clusters',
        'input_model': ListClustersRequest,
        'output_model': ListClustersResponse,
        'http_method': 'GET',
        'request_uri': '/prod/clusters',
        'auto_description': 'Retrieve the list of Clusters.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['Clusters'],
            'limit_key': 'MaxResults',
        },
    },
    'ListNetworks': {
        'name': 'ListNetworks',
        'tool_name': 'list_networks',
        'input_model': ListNetworksRequest,
        'output_model': ListNetworksResponse,
        'http_method': 'GET',
        'request_uri': '/prod/networks',
        'auto_description': 'Retrieve the list of Networks.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['Networks'],
            'limit_key': 'MaxResults',
        },
    },
    'ListNodes': {
        'name': 'ListNodes',
        'tool_name': 'list_nodes',
        'input_model': ListNodesRequest,
        'output_model': ListNodesResponse,
        'http_method': 'GET',
        'request_uri': '/prod/clusters/{clusterId}/nodes',
        'auto_description': 'Retrieve the list of Nodes.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['Nodes'],
            'limit_key': 'MaxResults',
        },
    },
    'UpdateChannelPlacementGroup': {
        'name': 'UpdateChannelPlacementGroup',
        'tool_name': 'update_channel_placement_group',
        'input_model': UpdateChannelPlacementGroupRequest,
        'output_model': UpdateChannelPlacementGroupResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/clusters/{clusterId}/channelplacementgroups/{channelPlacementGroupId}',
        'auto_description': 'Change the settings for a ChannelPlacementGroup.',
        'pagination': None,
    },
    'UpdateCluster': {
        'name': 'UpdateCluster',
        'tool_name': 'update_cluster',
        'input_model': UpdateClusterRequest,
        'output_model': UpdateClusterResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/clusters/{clusterId}',
        'auto_description': 'Change the settings for a Cluster.',
        'pagination': None,
    },
    'UpdateNetwork': {
        'name': 'UpdateNetwork',
        'tool_name': 'update_network',
        'input_model': UpdateNetworkRequest,
        'output_model': UpdateNetworkResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/networks/{networkId}',
        'auto_description': 'Change the settings for a Network.',
        'pagination': None,
    },
    'UpdateNode': {
        'name': 'UpdateNode',
        'tool_name': 'update_node',
        'input_model': UpdateNodeRequest,
        'output_model': UpdateNodeResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/clusters/{clusterId}/nodes/{nodeId}',
        'auto_description': 'Change the settings for a Node.',
        'pagination': None,
    },
    'UpdateNodeState': {
        'name': 'UpdateNodeState',
        'tool_name': 'update_node_state',
        'input_model': UpdateNodeStateRequest,
        'output_model': UpdateNodeStateResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/clusters/{clusterId}/nodes/{nodeId}/state',
        'auto_description': 'Update the state of a node.',
        'pagination': None,
    },
    'ListVersions': {
        'name': 'ListVersions',
        'tool_name': 'list_versions',
        'input_model': ListVersionsRequest,
        'output_model': ListVersionsResponse,
        'http_method': 'GET',
        'request_uri': '/prod/versions',
        'auto_description': 'Retrieves an array of all the encoder engine versions that are available in this AWS account.',
        'pagination': None,
    },
    'CreateSdiSource': {
        'name': 'CreateSdiSource',
        'tool_name': 'create_sdi_source',
        'input_model': CreateSdiSourceRequest,
        'output_model': CreateSdiSourceResponse,
        'http_method': 'POST',
        'request_uri': '/prod/sdiSources',
        'auto_description': 'Create an SdiSource for each video source that uses the SDI protocol. You will reference the SdiSource when you create an SDI input in MediaLive. You will also reference it in an SdiSourceMapping, in order to create a connection between the logical SdiSource and the physical SDI card and port that the physical SDI source uses.',
        'pagination': None,
    },
    'DeleteSdiSource': {
        'name': 'DeleteSdiSource',
        'tool_name': 'delete_sdi_source',
        'input_model': DeleteSdiSourceRequest,
        'output_model': DeleteSdiSourceResponse,
        'http_method': 'DELETE',
        'request_uri': '/prod/sdiSources/{sdiSourceId}',
        'auto_description': 'Delete an SdiSource. The SdiSource must not be part of any SidSourceMapping and must not be attached to any input.',
        'pagination': None,
    },
    'DescribeSdiSource': {
        'name': 'DescribeSdiSource',
        'tool_name': 'describe_sdi_source',
        'input_model': DescribeSdiSourceRequest,
        'output_model': DescribeSdiSourceResponse,
        'http_method': 'GET',
        'request_uri': '/prod/sdiSources/{sdiSourceId}',
        'auto_description': 'Gets details about a SdiSource.',
        'pagination': None,
    },
    'ListSdiSources': {
        'name': 'ListSdiSources',
        'tool_name': 'list_sdi_sources',
        'input_model': ListSdiSourcesRequest,
        'output_model': ListSdiSourcesResponse,
        'http_method': 'GET',
        'request_uri': '/prod/sdiSources',
        'auto_description': 'List all the SdiSources in the AWS account.',
        'pagination': {
            'input_tokens': ['NextToken'],
            'output_tokens': ['NextToken'],
            'result_keys': ['SdiSources'],
            'limit_key': 'MaxResults',
        },
    },
    'UpdateSdiSource': {
        'name': 'UpdateSdiSource',
        'tool_name': 'update_sdi_source',
        'input_model': UpdateSdiSourceRequest,
        'output_model': UpdateSdiSourceResponse,
        'http_method': 'PUT',
        'request_uri': '/prod/sdiSources/{sdiSourceId}',
        'auto_description': 'Change some of the settings in an SdiSource.',
        'pagination': None,
    },
}
