name: Python

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Build Python Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatchling
          pip install -e .

      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check .
          ruff format --check .

      - name: Build package
        run: |
          python -m pip install build
          python -m build
