---
# Tests the reuseable workflow for the core-mcp-server
name: Build and Push Container Image Tester
on:
  push:
    branches: ["feature/push-container-images"]

permissions: {}

jobs:
  go-go-reusable-workflow:
    name: go-go ${{ matrix.package }}
    # https://github.com/.github/workflows/tree/feature/push-container-images/build-and-push-container-image.yml
    uses: awslabs/mcp/.github/workflows/build-and-push-container-image.yml@feature/push-container-images
    # uses: .github/workflows/build-and-push-container-image.yml
    permissions:
      contents: read
      packages: write
      actions: read
    secrets: inherit # pragma: allowlist secret
    with:
      image: ${{ matrix.package }}
      version: ${{ github.run_id }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - core-mcp-server
          - git-repo-research-mcp-server

  next-jobs:
    name: Next Job
    permissions:
      contents: read
    runs-on: ubuntu-latest     
    steps:
      - run: |
          echo "go"
      - uses: awslabs/mcp/.github/actions/build-and-push-container-image@feature/push-container-images
        with:
          secrets: inherit
          image: 'test-mcp-server'
          version: 'TBD'
