---
# Tests the reuseable workflow for the core-mcp-server
name: Build and Push Container Image Tester
on:
  push:
    branches: ["feature/push-container-images"]

permissions: {}

jobs:

  test-action:
    name: Test Job
    permissions:
      contents: read
      id-token: write
      packages: write

    runs-on: ubuntu-latest
    environment: release
    strategy:
      fail-fast: false
      matrix:
        package:
          - core-mcp-server
          - git-repo-research-mcp-server

    steps:
      - name: Checkout repository
        id: checkout-repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build and Publish ${{ matrix.package }}
        id: build-and-publish
        uses: ./.github/actions/build-and-push-container-image
        if: hashFiles(format('./src/{0}/Dockerfile', matrix.package))
        with:
          image: ${{ matrix.package }}
          version: ${{ github.sha }}
          docker-hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-hub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          github-container-registry-token: ${{ github.token }}
          public-erc-role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
          public-erc-aws-region: ${{ env.AWS_REGION || 'us-east-1' }}

      - name: Display Image Version ${{ matrix.package }}
        id: display-image-version
        if: success() && steps.build-and-publish.outcome == 'success'
        run: |
          echo "version: ${VERSION}"
        env:
          VERSION: ${{ steps.build-and-publish.outputs.version }}

      - name: Continue
        run: |
          echo "continue"
